# ####################################################################

#  Created by Genus(TM) Synthesis Solution 16.23-s049_1 on Fri Sep 18 11:27:12 +0530 2026

# ####################################################################

set sdc_version 1.7

set_units -capacitance 1000.0fF
set_units -time 1000.0ps

# Set the current design
current_design sync_fifo

create_clock -name "clk_i" -add -period 4.0 -waveform {0.0 2.0} [get_ports clk_i]
set_clock_transition 0.2 [get_clocks clk_i]
set_load -pin_load 0.05 [get_ports {rd_data_o[7]}]
set_load -pin_load 0.05 [get_ports {rd_data_o[6]}]
set_load -pin_load 0.05 [get_ports {rd_data_o[5]}]
set_load -pin_load 0.05 [get_ports {rd_data_o[4]}]
set_load -pin_load 0.05 [get_ports {rd_data_o[3]}]
set_load -pin_load 0.05 [get_ports {rd_data_o[2]}]
set_load -pin_load 0.05 [get_ports {rd_data_o[1]}]
set_load -pin_load 0.05 [get_ports {rd_data_o[0]}]
set_load -pin_load 0.05 [get_ports full_o]
set_load -pin_load 0.05 [get_ports empty_o]
set_load -pin_load 0.05 [get_ports error_o]
set_clock_gating_check -setup 0.0 
set_input_delay -clock [get_clocks clk_i] -add_delay -max 1.6 [get_ports rst_i]
set_input_delay -clock [get_clocks clk_i] -add_delay -max 1.6 [get_ports wr_en_i]
set_input_delay -clock [get_clocks clk_i] -add_delay -max 1.6 [get_ports rd_en_i]
set_input_delay -clock [get_clocks clk_i] -add_delay -min 0.4 [get_ports rst_i]
set_input_delay -clock [get_clocks clk_i] -add_delay -min 0.4 [get_ports wr_en_i]
set_input_delay -clock [get_clocks clk_i] -add_delay -min 0.4 [get_ports rd_en_i]
set_input_delay -clock [get_clocks clk_i] -add_delay -max 1.6 [get_ports {wr_data_i[7]}]
set_input_delay -clock [get_clocks clk_i] -add_delay -max 1.6 [get_ports {wr_data_i[6]}]
set_input_delay -clock [get_clocks clk_i] -add_delay -max 1.6 [get_ports {wr_data_i[5]}]
set_input_delay -clock [get_clocks clk_i] -add_delay -max 1.6 [get_ports {wr_data_i[4]}]
set_input_delay -clock [get_clocks clk_i] -add_delay -max 1.6 [get_ports {wr_data_i[3]}]
set_input_delay -clock [get_clocks clk_i] -add_delay -max 1.6 [get_ports {wr_data_i[2]}]
set_input_delay -clock [get_clocks clk_i] -add_delay -max 1.6 [get_ports {wr_data_i[1]}]
set_input_delay -clock [get_clocks clk_i] -add_delay -max 1.6 [get_ports {wr_data_i[0]}]
set_input_delay -clock [get_clocks clk_i] -add_delay -min 0.4 [get_ports {wr_data_i[7]}]
set_input_delay -clock [get_clocks clk_i] -add_delay -min 0.4 [get_ports {wr_data_i[6]}]
set_input_delay -clock [get_clocks clk_i] -add_delay -min 0.4 [get_ports {wr_data_i[5]}]
set_input_delay -clock [get_clocks clk_i] -add_delay -min 0.4 [get_ports {wr_data_i[4]}]
set_input_delay -clock [get_clocks clk_i] -add_delay -min 0.4 [get_ports {wr_data_i[3]}]
set_input_delay -clock [get_clocks clk_i] -add_delay -min 0.4 [get_ports {wr_data_i[2]}]
set_input_delay -clock [get_clocks clk_i] -add_delay -min 0.4 [get_ports {wr_data_i[1]}]
set_input_delay -clock [get_clocks clk_i] -add_delay -min 0.4 [get_ports {wr_data_i[0]}]
set_output_delay -clock [get_clocks clk_i] -add_delay -max 1.6 [get_ports {rd_data_o[7]}]
set_output_delay -clock [get_clocks clk_i] -add_delay -max 1.6 [get_ports {rd_data_o[6]}]
set_output_delay -clock [get_clocks clk_i] -add_delay -max 1.6 [get_ports {rd_data_o[5]}]
set_output_delay -clock [get_clocks clk_i] -add_delay -max 1.6 [get_ports {rd_data_o[4]}]
set_output_delay -clock [get_clocks clk_i] -add_delay -max 1.6 [get_ports {rd_data_o[3]}]
set_output_delay -clock [get_clocks clk_i] -add_delay -max 1.6 [get_ports {rd_data_o[2]}]
set_output_delay -clock [get_clocks clk_i] -add_delay -max 1.6 [get_ports {rd_data_o[1]}]
set_output_delay -clock [get_clocks clk_i] -add_delay -max 1.6 [get_ports {rd_data_o[0]}]
set_output_delay -clock [get_clocks clk_i] -add_delay -max 1.6 [get_ports full_o]
set_output_delay -clock [get_clocks clk_i] -add_delay -max 1.6 [get_ports empty_o]
set_output_delay -clock [get_clocks clk_i] -add_delay -max 1.6 [get_ports error_o]
set_output_delay -clock [get_clocks clk_i] -add_delay -min 0.4 [get_ports {rd_data_o[7]}]
set_output_delay -clock [get_clocks clk_i] -add_delay -min 0.4 [get_ports {rd_data_o[6]}]
set_output_delay -clock [get_clocks clk_i] -add_delay -min 0.4 [get_ports {rd_data_o[5]}]
set_output_delay -clock [get_clocks clk_i] -add_delay -min 0.4 [get_ports {rd_data_o[4]}]
set_output_delay -clock [get_clocks clk_i] -add_delay -min 0.4 [get_ports {rd_data_o[3]}]
set_output_delay -clock [get_clocks clk_i] -add_delay -min 0.4 [get_ports {rd_data_o[2]}]
set_output_delay -clock [get_clocks clk_i] -add_delay -min 0.4 [get_ports {rd_data_o[1]}]
set_output_delay -clock [get_clocks clk_i] -add_delay -min 0.4 [get_ports {rd_data_o[0]}]
set_output_delay -clock [get_clocks clk_i] -add_delay -min 0.4 [get_ports full_o]
set_output_delay -clock [get_clocks clk_i] -add_delay -min 0.4 [get_ports empty_o]
set_output_delay -clock [get_clocks clk_i] -add_delay -min 0.4 [get_ports error_o]
set_driving_cell -lib_cell BUFX2 -library slow_vdd1v0 -pin "Y" [get_ports rst_i]
set_driving_cell -lib_cell BUFX2 -library slow_vdd1v0 -pin "Y" [get_ports wr_en_i]
set_driving_cell -lib_cell BUFX2 -library slow_vdd1v0 -pin "Y" [get_ports rd_en_i]
set_driving_cell -lib_cell BUFX2 -library slow_vdd1v0 -pin "Y" [get_ports {wr_data_i[7]}]
set_driving_cell -lib_cell BUFX2 -library slow_vdd1v0 -pin "Y" [get_ports {wr_data_i[6]}]
set_driving_cell -lib_cell BUFX2 -library slow_vdd1v0 -pin "Y" [get_ports {wr_data_i[5]}]
set_driving_cell -lib_cell BUFX2 -library slow_vdd1v0 -pin "Y" [get_ports {wr_data_i[4]}]
set_driving_cell -lib_cell BUFX2 -library slow_vdd1v0 -pin "Y" [get_ports {wr_data_i[3]}]
set_driving_cell -lib_cell BUFX2 -library slow_vdd1v0 -pin "Y" [get_ports {wr_data_i[2]}]
set_driving_cell -lib_cell BUFX2 -library slow_vdd1v0 -pin "Y" [get_ports {wr_data_i[1]}]
set_driving_cell -lib_cell BUFX2 -library slow_vdd1v0 -pin "Y" [get_ports {wr_data_i[0]}]
set_wire_load_mode "enclosed"
set_dont_use [get_lib_cells slow_vdd1v0/HOLDX1]
set_dont_use [get_lib_cells slow_vdd1v0/MDFFHQX1]
set_dont_use [get_lib_cells slow_vdd1v0/MDFFHQX2]
set_dont_use [get_lib_cells slow_vdd1v0/MDFFHQX4]
set_dont_use [get_lib_cells slow_vdd1v0/MDFFHQX8]
set_dont_use [get_lib_cells slow_vdd1v0/SDFFHQX1]
set_dont_use [get_lib_cells slow_vdd1v0/SDFFHQX2]
set_dont_use [get_lib_cells slow_vdd1v0/SDFFHQX4]
set_dont_use [get_lib_cells slow_vdd1v0/SDFFHQX8]
set_dont_use [get_lib_cells slow_vdd1v0/SDFFNSRX1]
set_dont_use [get_lib_cells slow_vdd1v0/SDFFNSRX2]
set_dont_use [get_lib_cells slow_vdd1v0/SDFFNSRX4]
set_dont_use [get_lib_cells slow_vdd1v0/SDFFNSRXL]
set_dont_use [get_lib_cells slow_vdd1v0/SDFFQX1]
set_dont_use [get_lib_cells slow_vdd1v0/SDFFQX2]
set_dont_use [get_lib_cells slow_vdd1v0/SDFFQX4]
set_dont_use [get_lib_cells slow_vdd1v0/SDFFQXL]
set_dont_use [get_lib_cells slow_vdd1v0/SDFFRHQX1]
set_dont_use [get_lib_cells slow_vdd1v0/SDFFRHQX2]
set_dont_use [get_lib_cells slow_vdd1v0/SDFFRHQX4]
set_dont_use [get_lib_cells slow_vdd1v0/SDFFRHQX8]
set_dont_use [get_lib_cells slow_vdd1v0/SDFFRX1]
set_dont_use [get_lib_cells slow_vdd1v0/SDFFRX2]
set_dont_use [get_lib_cells slow_vdd1v0/SDFFRX4]
set_dont_use [get_lib_cells slow_vdd1v0/SDFFRXL]
set_dont_use [get_lib_cells slow_vdd1v0/SDFFSHQX1]
set_dont_use [get_lib_cells slow_vdd1v0/SDFFSHQX2]
set_dont_use [get_lib_cells slow_vdd1v0/SDFFSHQX4]
set_dont_use [get_lib_cells slow_vdd1v0/SDFFSHQX8]
set_dont_use [get_lib_cells slow_vdd1v0/SDFFSRHQX1]
set_dont_use [get_lib_cells slow_vdd1v0/SDFFSRHQX2]
set_dont_use [get_lib_cells slow_vdd1v0/SDFFSRHQX4]
set_dont_use [get_lib_cells slow_vdd1v0/SDFFSRHQX8]
set_dont_use [get_lib_cells slow_vdd1v0/SDFFSRX1]
set_dont_use [get_lib_cells slow_vdd1v0/SDFFSRX2]
set_dont_use [get_lib_cells slow_vdd1v0/SDFFSRX4]
set_dont_use [get_lib_cells slow_vdd1v0/SDFFSRXL]
set_dont_use [get_lib_cells slow_vdd1v0/SDFFSX1]
set_dont_use [get_lib_cells slow_vdd1v0/SDFFSX2]
set_dont_use [get_lib_cells slow_vdd1v0/SDFFSX4]
set_dont_use [get_lib_cells slow_vdd1v0/SDFFSXL]
set_dont_use [get_lib_cells slow_vdd1v0/SDFFTRX1]
set_dont_use [get_lib_cells slow_vdd1v0/SDFFTRX2]
set_dont_use [get_lib_cells slow_vdd1v0/SDFFTRX4]
set_dont_use [get_lib_cells slow_vdd1v0/SDFFTRXL]
set_dont_use [get_lib_cells slow_vdd1v0/SDFFX1]
set_dont_use [get_lib_cells slow_vdd1v0/SDFFX2]
set_dont_use [get_lib_cells slow_vdd1v0/SDFFX4]
set_dont_use [get_lib_cells slow_vdd1v0/SDFFXL]
set_dont_use [get_lib_cells slow_vdd1v0/SMDFFHQX1]
set_dont_use [get_lib_cells slow_vdd1v0/SMDFFHQX2]
set_dont_use [get_lib_cells slow_vdd1v0/SMDFFHQX4]
set_dont_use [get_lib_cells slow_vdd1v0/SMDFFHQX8]
set_clock_uncertainty -setup 0.2 [get_clocks clk_i]
set_clock_uncertainty -hold 0.2 [get_clocks clk_i]
