
// Generated by Cadence Genus(TM) Synthesis Solution 16.23-s049_1
// Generated on: Sep 18 2026 11:56:18 IST (Sep 18 2026 06:26:18 UTC)

// Verification Directory fv/sync_fifo_edt_top 

`timescale 1ns / 1ns


module sync_fifo_edt_bypass_logic(edt_bypass, edt_channels_in,
     edt_channels_out, edt_scan_in, edt_scan_out, edt_bypass_in,
     edt_bypass_out);
  input edt_bypass;
  input [2:0] edt_channels_in, edt_scan_out, edt_bypass_in,
       edt_bypass_out;
  output [2:0] edt_channels_out, edt_scan_in;
  wire edt_bypass;
  wire [2:0] edt_channels_in, edt_scan_out, edt_bypass_in,
       edt_bypass_out;
  wire [2:0] edt_channels_out, edt_scan_in;
  MX2XL g107(.A (edt_bypass_out[2]), .B (edt_scan_out[2]), .S0
       (edt_bypass), .Y (edt_channels_out[2]));
  MX2XL g108(.A (edt_bypass_in[2]), .B (edt_channels_in[2]), .S0
       (edt_bypass), .Y (edt_scan_in[2]));
  MX2XL g109(.A (edt_bypass_in[1]), .B (edt_channels_in[1]), .S0
       (edt_bypass), .Y (edt_scan_in[1]));
  MX2XL g110(.A (edt_bypass_out[1]), .B (edt_scan_out[1]), .S0
       (edt_bypass), .Y (edt_channels_out[1]));
  MX2XL g111(.A (edt_bypass_out[0]), .B (edt_scan_out[0]), .S0
       (edt_bypass), .Y (edt_channels_out[0]));
  MX2XL g112(.A (edt_bypass_in[0]), .B (edt_channels_in[0]), .S0
       (edt_bypass), .Y (edt_scan_in[0]));
endmodule

module sync_fifo_edt_compactor(edt_scan_out, masks_for_compactor_0,
     masks_for_compactor_1, masks_for_compactor_2, edt_channels_out);
  input [2:0] edt_scan_out;
  input masks_for_compactor_0, masks_for_compactor_1,
       masks_for_compactor_2;
  output [2:0] edt_channels_out;
  wire [2:0] edt_scan_out;
  wire masks_for_compactor_0, masks_for_compactor_1,
       masks_for_compactor_2;
  wire [2:0] edt_channels_out;
  AND2X1 g22(.A (masks_for_compactor_2), .B (edt_scan_out[2]), .Y
       (edt_channels_out[2]));
  AND2X1 g23(.A (masks_for_compactor_1), .B (edt_scan_out[1]), .Y
       (edt_channels_out[1]));
  AND2X1 g24(.A (masks_for_compactor_0), .B (edt_scan_out[0]), .Y
       (edt_channels_out[0]));
endmodule

module sync_fifo_edt_controller(edt_clock, edt_update, edt_channels_in,
     edt_channels_out_from_controller, masks_for_compactor_0,
     masks_for_compactor_1, masks_for_compactor_2);
  input edt_clock, edt_update;
  input [2:0] edt_channels_in;
  output [2:0] edt_channels_out_from_controller;
  output masks_for_compactor_0, masks_for_compactor_1,
       masks_for_compactor_2;
  wire edt_clock, edt_update;
  wire [2:0] edt_channels_in;
  wire [2:0] edt_channels_out_from_controller;
  wire masks_for_compactor_0, masks_for_compactor_1,
       masks_for_compactor_2;
  wire [1:0] masks_shift_reg_0;
  wire n_0, n_1, n_2, n_3;
  DFFHQX1 \masks_shift_reg_0_reg[0] (.CK (edt_clock), .D (n_3), .Q
       (edt_channels_out_from_controller[0]));
  NOR2BX1 g19(.AN (masks_shift_reg_0[1]), .B (edt_update), .Y (n_3));
  DFFHQX1 masks_shift_reg_1_reg(.CK (edt_clock), .D (n_2), .Q
       (edt_channels_out_from_controller[1]));
  DFFQXL \masks_shift_reg_0_reg[1] (.CK (edt_clock), .D (n_1), .Q
       (masks_shift_reg_0[1]));
  DFFHQX1 masks_shift_reg_2_reg(.CK (edt_clock), .D (n_0), .Q
       (edt_channels_out_from_controller[2]));
  NOR2BX1 g23(.AN (edt_channels_in[1]), .B (edt_update), .Y (n_2));
  NOR2BX1 g24(.AN (edt_channels_in[0]), .B (edt_update), .Y (n_1));
  NOR2BX1 g25(.AN (edt_channels_in[2]), .B (edt_update), .Y (n_0));
  SDFFQX1 \masks_hold_reg_0_reg[0] (.CK (edt_clock), .D
       (masks_for_compactor_0), .SI
       (edt_channels_out_from_controller[0]), .SE (edt_update), .Q
       (masks_for_compactor_0));
  SDFFQX1 masks_hold_reg_1_reg(.CK (edt_clock), .D
       (masks_for_compactor_1), .SI
       (edt_channels_out_from_controller[1]), .SE (edt_update), .Q
       (masks_for_compactor_1));
  SDFFQX1 masks_hold_reg_2_reg(.CK (edt_clock), .D
       (masks_for_compactor_2), .SI
       (edt_channels_out_from_controller[2]), .SE (edt_update), .Q
       (masks_for_compactor_2));
endmodule

module sync_fifo_edt_decompressor(edt_clock, edt_update,
     edt_channels_in, edt_scan_in);
  input edt_clock, edt_update;
  input [2:0] edt_channels_in;
  output [2:0] edt_scan_in;
  wire edt_clock, edt_update;
  wire [2:0] edt_channels_in;
  wire [2:0] edt_scan_in;
  wire [15:0] lfsm_vec_lockup;
  wire [15:0] lfsm_vec;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28;
  XNOR2X1 g141(.A (lfsm_vec_lockup[9]), .B (n_28), .Y (edt_scan_in[0]));
  XNOR2X1 g142(.A (lfsm_vec_lockup[8]), .B (lfsm_vec_lockup[6]), .Y
       (n_28));
  DFFNSRX1 \lfsm_vec_lockup_reg[8] (.RN (1'b1), .SN (1'b1), .CKN
       (edt_clock), .D (lfsm_vec[8]), .Q (lfsm_vec_lockup[8]), .QN
       (UNCONNECTED));
  DFFQXL \lfsm_vec_reg[8] (.CK (edt_clock), .D (n_27), .Q
       (lfsm_vec[8]));
  NOR2X1 g145(.A (edt_update), .B (n_26), .Y (n_27));
  XNOR2X1 g146(.A (lfsm_vec_lockup[15]), .B (n_25), .Y
       (edt_scan_in[2]));
  XNOR2X1 g147(.A (lfsm_vec[9]), .B (lfsm_vec[6]), .Y (n_26));
  DFFNSRX1 \lfsm_vec_lockup_reg[9] (.RN (1'b1), .SN (1'b1), .CKN
       (edt_clock), .D (lfsm_vec[9]), .Q (lfsm_vec_lockup[9]), .QN
       (UNCONNECTED0));
  XNOR2X1 g149(.A (lfsm_vec_lockup[10]), .B (lfsm_vec_lockup[3]), .Y
       (n_25));
  DFFQXL \lfsm_vec_reg[9] (.CK (edt_clock), .D (n_24), .Q
       (lfsm_vec[9]));
  DFFNSRX1 \lfsm_vec_lockup_reg[10] (.RN (1'b1), .SN (1'b1), .CKN
       (edt_clock), .D (lfsm_vec[10]), .Q (lfsm_vec_lockup[10]), .QN
       (UNCONNECTED1));
  NOR2BX1 g152(.AN (lfsm_vec[10]), .B (edt_update), .Y (n_24));
  DFFQXL \lfsm_vec_reg[10] (.CK (edt_clock), .D (n_23), .Q
       (lfsm_vec[10]));
  NOR2X1 g154(.A (edt_update), .B (n_22), .Y (n_23));
  XNOR2X1 g155(.A (lfsm_vec[11]), .B (edt_channels_in[0]), .Y (n_22));
  DFFHQX1 \lfsm_vec_reg[11] (.CK (edt_clock), .D (n_21), .Q
       (lfsm_vec[11]));
  NOR2X1 g157(.A (edt_update), .B (n_20), .Y (n_21));
  XNOR2X1 g158(.A (lfsm_vec[12]), .B (lfsm_vec[5]), .Y (n_20));
  DFFHQX1 \lfsm_vec_reg[12] (.CK (edt_clock), .D (n_19), .Q
       (lfsm_vec[12]));
  NOR2X1 g160(.A (edt_update), .B (n_18), .Y (n_19));
  XNOR2X1 g161(.A (lfsm_vec_lockup[13]), .B (n_13), .Y
       (edt_scan_in[1]));
  XNOR2X1 g162(.A (lfsm_vec[13]), .B (lfsm_vec[3]), .Y (n_18));
  DFFNSRX1 \lfsm_vec_lockup_reg[13] (.RN (1'b1), .SN (1'b1), .CKN
       (edt_clock), .D (lfsm_vec[13]), .Q (lfsm_vec_lockup[13]), .QN
       (UNCONNECTED2));
  DFFQXL \lfsm_vec_reg[13] (.CK (edt_clock), .D (n_17), .Q
       (lfsm_vec[13]));
  NOR2X1 g165(.A (edt_update), .B (n_16), .Y (n_17));
  XNOR2X1 g166(.A (lfsm_vec[14]), .B (edt_channels_in[2]), .Y (n_16));
  DFFQXL \lfsm_vec_reg[14] (.CK (edt_clock), .D (n_15), .Q
       (lfsm_vec[14]));
  DFFNSRX1 \lfsm_vec_lockup_reg[15] (.RN (1'b1), .SN (1'b1), .CKN
       (edt_clock), .D (lfsm_vec[15]), .Q (lfsm_vec_lockup[15]), .QN
       (UNCONNECTED3));
  NOR2BX1 g169(.AN (lfsm_vec[15]), .B (edt_update), .Y (n_15));
  DFFQXL \lfsm_vec_reg[15] (.CK (edt_clock), .D (n_14), .Q
       (lfsm_vec[15]));
  NOR2X1 g171(.A (edt_update), .B (n_12), .Y (n_14));
  XNOR2X1 g172(.A (lfsm_vec_lockup[4]), .B (lfsm_vec_lockup[1]), .Y
       (n_13));
  XNOR2X1 g173(.A (lfsm_vec[0]), .B (edt_channels_in[0]), .Y (n_12));
  DFFNSRX1 \lfsm_vec_lockup_reg[4] (.RN (1'b1), .SN (1'b1), .CKN
       (edt_clock), .D (lfsm_vec[4]), .Q (lfsm_vec_lockup[4]), .QN
       (UNCONNECTED4));
  DFFQXL \lfsm_vec_reg[4] (.CK (edt_clock), .D (n_10), .Q
       (lfsm_vec[4]));
  DFFHQX1 \lfsm_vec_reg[0] (.CK (edt_clock), .D (n_11), .Q
       (lfsm_vec[0]));
  DFFNSRX1 \lfsm_vec_lockup_reg[1] (.RN (1'b1), .SN (1'b1), .CKN
       (edt_clock), .D (lfsm_vec[1]), .Q (lfsm_vec_lockup[1]), .QN
       (UNCONNECTED5));
  DFFNSRX1 \lfsm_vec_lockup_reg[3] (.RN (1'b1), .SN (1'b1), .CKN
       (edt_clock), .D (lfsm_vec[3]), .Q (lfsm_vec_lockup[3]), .QN
       (UNCONNECTED6));
  NOR2BX1 g179(.AN (lfsm_vec[1]), .B (edt_update), .Y (n_11));
  NOR2BX1 g180(.AN (lfsm_vec[5]), .B (edt_update), .Y (n_10));
  DFFNSRX1 \lfsm_vec_lockup_reg[6] (.RN (1'b1), .SN (1'b1), .CKN
       (edt_clock), .D (lfsm_vec[6]), .Q (lfsm_vec_lockup[6]), .QN
       (UNCONNECTED7));
  DFFHQX1 \lfsm_vec_reg[1] (.CK (edt_clock), .D (n_7), .Q
       (lfsm_vec[1]));
  DFFHQX1 \lfsm_vec_reg[6] (.CK (edt_clock), .D (n_8), .Q
       (lfsm_vec[6]));
  NOR2BX1 g55(.AN (lfsm_vec[7]), .B (edt_update), .Y (n_8));
  NOR2BX1 g56(.AN (lfsm_vec[2]), .B (edt_update), .Y (n_7));
  DFFHQX1 \lfsm_vec_reg[5] (.CK (edt_clock), .D (n_6), .Q
       (lfsm_vec[5]));
  DFFHQX1 \lfsm_vec_reg[7] (.CK (edt_clock), .D (n_5), .Q
       (lfsm_vec[7]));
  DFFHQX1 \lfsm_vec_reg[2] (.CK (edt_clock), .D (n_4), .Q
       (lfsm_vec[2]));
  NOR2X1 g60(.A (edt_update), .B (n_2), .Y (n_6));
  NOR2X1 g61(.A (edt_update), .B (n_1), .Y (n_5));
  NOR2X1 g62(.A (edt_update), .B (n_3), .Y (n_4));
  XNOR2X1 g63(.A (edt_channels_in[1]), .B (lfsm_vec[3]), .Y (n_3));
  DFFHQX1 \lfsm_vec_reg[3] (.CK (edt_clock), .D (n_0), .Q
       (lfsm_vec[3]));
  XNOR2X1 g65(.A (edt_channels_in[2]), .B (lfsm_vec[6]), .Y (n_2));
  XNOR2X1 g66(.A (lfsm_vec[8]), .B (edt_channels_in[1]), .Y (n_1));
  NOR2BX1 g67(.AN (lfsm_vec[4]), .B (edt_update), .Y (n_0));
endmodule

module sync_fifo_edt(edt_clock, edt_update, edt_bypass,
     edt_channels_in, edt_channels_out, edt_scan_in, edt_scan_out);
  input edt_clock, edt_update, edt_bypass;
  input [2:0] edt_channels_in, edt_scan_out;
  output [2:0] edt_channels_out, edt_scan_in;
  wire edt_clock, edt_update, edt_bypass;
  wire [2:0] edt_channels_in, edt_scan_out;
  wire [2:0] edt_channels_out, edt_scan_in;
  wire [2:0] edt_bypass_in;
  wire [2:0] edt_bypass_out;
  wire [2:0] edt_channels_out_from_controller;
  wire masks_for_compactor_0, masks_for_compactor_1,
       masks_for_compactor_2;
  sync_fifo_edt_bypass_logic sync_fifo_edt_bypass_logic_i(.edt_bypass
       (edt_bypass), .edt_channels_in (edt_channels_in),
       .edt_channels_out (edt_channels_out), .edt_scan_in
       (edt_scan_in), .edt_scan_out (edt_scan_out), .edt_bypass_in
       (edt_bypass_in), .edt_bypass_out (edt_bypass_out));
  sync_fifo_edt_compactor sync_fifo_edt_compactor_i(.edt_scan_out
       (edt_scan_out), .masks_for_compactor_0 (masks_for_compactor_0),
       .masks_for_compactor_1 (masks_for_compactor_1),
       .masks_for_compactor_2 (masks_for_compactor_2),
       .edt_channels_out (edt_bypass_out));
  sync_fifo_edt_controller sync_fifo_edt_controller_i(.edt_clock
       (edt_clock), .edt_update (edt_update), .edt_channels_in
       (edt_channels_in), .edt_channels_out_from_controller
       (edt_channels_out_from_controller), .masks_for_compactor_0
       (masks_for_compactor_0), .masks_for_compactor_1
       (masks_for_compactor_1), .masks_for_compactor_2
       (masks_for_compactor_2));
  sync_fifo_edt_decompressor sync_fifo_edt_decompressor_i(.edt_clock
       (edt_clock), .edt_update (edt_update), .edt_channels_in
       (edt_channels_out_from_controller), .edt_scan_in
       (edt_bypass_in));
endmodule

module sync_fifo(clk_i, rst_i, wr_en_i, rd_en_i, wr_data_i, rd_data_o,
     full_o, empty_o, error_o, ts_si, ts_so, scan_en);
  input clk_i, rst_i, wr_en_i, rd_en_i, scan_en;
  input [7:0] wr_data_i;
  input [2:0] ts_si;
  output [7:0] rd_data_o;
  output full_o, empty_o, error_o;
  output [2:0] ts_so;
  wire clk_i, rst_i, wr_en_i, rd_en_i, scan_en;
  wire [7:0] wr_data_i;
  wire [2:0] ts_si;
  wire [7:0] rd_data_o;
  wire full_o, empty_o, error_o;
  wire [2:0] ts_so;
  wire [7:0] \fifo[8] ;
  wire [7:0] \fifo[9] ;
  wire [7:0] \fifo[4] ;
  wire [7:0] \fifo[12] ;
  wire [7:0] \fifo[2] ;
  wire [7:0] \fifo[15] ;
  wire [7:0] \fifo[0] ;
  wire [7:0] \fifo[11] ;
  wire [7:0] \fifo[13] ;
  wire [7:0] \fifo[5] ;
  wire [7:0] \fifo[7] ;
  wire [7:0] \fifo[10] ;
  wire [7:0] \fifo[1] ;
  wire [7:0] \fifo[3] ;
  wire [7:0] \fifo[14] ;
  wire [7:0] \fifo[6] ;
  wire [3:0] rd_ptr;
  wire [3:0] wr_ptr;
  wire UNCONNECTED8, UNCONNECTED9, UNCONNECTED10, n_0, n_1, n_2, n_4,
       n_5;
  wire n_6, n_7, n_8, n_9, n_10, n_11, n_12, n_13;
  wire n_14, n_15, n_16, n_17, n_18, n_19, n_20, n_21;
  wire n_22, n_25, n_26, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_41;
  wire n_42, n_44, n_45, n_46, n_47, n_48, n_49, n_50;
  wire n_51, n_52, n_53, n_54, n_55, n_56, n_57, n_58;
  wire n_59, n_60, n_61, n_62, n_63, n_64, n_65, n_66;
  wire n_67, n_68, n_69, n_70, n_71, n_72, n_73, n_74;
  wire n_75, n_76, n_77, n_78, n_79, n_80, n_81, n_82;
  wire n_83, n_84, n_85, n_86, n_87, n_88, n_89, n_90;
  wire n_91, n_92, n_93, n_94, n_95, n_96, n_97, n_98;
  wire n_99, n_100, n_101, n_102, n_103, n_104, n_105, n_106;
  wire n_107, n_108, n_109, n_110, n_111, n_112, n_113, n_114;
  wire n_115, n_116, n_117, n_118, n_119, n_120, n_121, n_122;
  wire n_123, n_124, n_125, n_126, n_127, n_128, n_129, n_130;
  wire n_131, n_132, n_133, n_134, n_135, n_136, n_137, n_138;
  wire n_139, n_140, n_141, n_142, n_143, n_144, n_145, n_146;
  wire n_147, n_148, n_149, n_150, n_151, n_152, n_153, n_154;
  wire n_155, n_156, n_157, n_158, n_159, n_160, n_161, n_162;
  wire n_163, n_164, n_165, n_166, n_167, n_168, n_169, n_170;
  wire n_171, n_172, n_173, n_174, n_175, n_176, n_177, n_178;
  wire n_179, n_180, n_181, n_182, n_183, n_184, n_185, n_186;
  wire n_187, n_188, n_189, n_190, n_191, n_192, n_193, n_194;
  wire n_195, n_196, n_197, n_198, n_199, n_200, n_201, n_202;
  wire n_203, n_204, n_205, n_206, n_207, n_208, n_209, n_210;
  wire n_212, n_213, n_214, n_215, n_216, n_217, n_218, n_219;
  wire n_220, n_221, n_222, n_223, n_224, n_225, n_226, n_227;
  wire n_228, n_229, n_230, n_231, n_232, n_233, n_234, n_235;
  wire n_236, n_237, n_238, n_239, n_241, n_242, n_243, n_244;
  wire n_245, n_246, n_247, n_248, n_249, n_250, n_251, n_252;
  wire n_253, n_254, n_255, n_256, n_257, n_258, n_259, n_260;
  wire n_261, n_262, n_263, n_264, n_265, n_266, n_267, n_268;
  wire n_269, n_270, n_271, n_272, n_273, n_274, n_275, n_276;
  wire n_277, n_278, n_279, n_280, n_281, n_282, n_283, n_284;
  wire n_285, n_286, n_287, n_288, n_289, n_290, n_291, n_292;
  wire n_293, n_294, n_295, n_296, n_297, n_298, n_299, n_300;
  wire n_301, n_302, n_303, n_304, n_305, n_306, n_307, n_308;
  wire n_309, n_310, n_311, n_312, n_313, n_314, n_315, n_316;
  wire n_317, n_318, n_319, n_320, n_321, n_322, n_323, n_324;
  wire n_325, n_326, n_327, n_328, n_329, n_330, n_331, n_332;
  wire n_333, n_334, n_335, n_336, n_337, n_338, n_339, n_340;
  wire n_341, n_342, n_343, n_344, n_345, n_346, n_347, n_348;
  wire n_362, n_363, n_364, rd_toggle_flag, ts_pbuf_extsi147_,
       ts_pbuf_extsi148_, ts_pbuf_extsi149_, wr_toggle_flag;
  SDFFHQX8 \rd_data_o_reg[0] (.CK (clk_i), .D (n_347), .SI
       (ts_pbuf_extsi147_), .SE (scan_en), .Q (rd_data_o[0]));
  SDFFHQX8 \rd_data_o_reg[6] (.CK (clk_i), .D (n_343), .SI
       (rd_data_o[0]), .SE (scan_en), .Q (rd_data_o[6]));
  SDFFHQX8 \rd_data_o_reg[1] (.CK (clk_i), .D (n_346), .SI
       (rd_data_o[6]), .SE (scan_en), .Q (rd_data_o[1]));
  SDFFHQX8 \rd_data_o_reg[3] (.CK (clk_i), .D (n_344), .SI
       (rd_data_o[1]), .SE (scan_en), .Q (rd_data_o[3]));
  SDFFHQX8 \rd_data_o_reg[4] (.CK (clk_i), .D (n_345), .SI
       (rd_data_o[3]), .SE (scan_en), .Q (rd_data_o[4]));
  SDFFHQX8 \rd_data_o_reg[5] (.CK (clk_i), .D (n_348), .SI
       (rd_data_o[4]), .SE (scan_en), .Q (rd_data_o[5]));
  SDFFHQX8 \rd_data_o_reg[7] (.CK (clk_i), .D (n_342), .SI
       (rd_data_o[5]), .SE (scan_en), .Q (rd_data_o[7]));
  SDFFHQX8 \rd_data_o_reg[2] (.CK (clk_i), .D (n_341), .SI
       (rd_data_o[7]), .SE (scan_en), .Q (rd_data_o[2]));
  NAND4BX1 g7363__7837(.AN (n_340), .B (n_100), .C (n_329), .D (n_309),
       .Y (n_348));
  NAND4BX1 g7359__7557(.AN (n_338), .B (n_93), .C (n_322), .D (n_316),
       .Y (n_347));
  NAND4BX1 g7360__7654(.AN (n_337), .B (n_98), .C (n_323), .D (n_314),
       .Y (n_346));
  NAND4BX1 g7364__8867(.AN (n_335), .B (n_109), .C (n_330), .D (n_312),
       .Y (n_345));
  NAND4BX1 g7365__1377(.AN (n_336), .B (n_85), .C (n_326), .D (n_313),
       .Y (n_344));
  NAND4BX1 g7366__3717(.AN (n_339), .B (n_102), .C (n_307), .D (n_308),
       .Y (n_343));
  NAND4BX1 g7367__4599(.AN (n_317), .B (n_154), .C (n_321), .D (n_334),
       .Y (n_342));
  NAND4BX1 g7368__3779(.AN (n_318), .B (n_137), .C (n_324), .D (n_333),
       .Y (n_341));
  NAND4XL g7432__2007(.A (n_266), .B (n_127), .C (n_129), .D (n_267),
       .Y (n_340));
  NAND4XL g7433__1237(.A (n_281), .B (n_155), .C (n_156), .D (n_291),
       .Y (n_339));
  NAND4XL g7434__1297(.A (n_276), .B (n_143), .C (n_144), .D (n_278),
       .Y (n_338));
  NAND4XL g7435__2006(.A (n_140), .B (n_139), .C (n_273), .D (n_274),
       .Y (n_337));
  NAND4XL g7436__2833(.A (n_269), .B (n_134), .C (n_146), .D (n_270),
       .Y (n_336));
  NAND4XL g7437__7547(.A (n_272), .B (n_130), .C (n_132), .D (n_268),
       .Y (n_335));
  AOI221X1 g7508__7765(.A0 (\fifo[8] [7]), .A1 (n_332), .B0
       (\fifo[9] [7]), .B1 (n_331), .C0 (n_152), .Y (n_334));
  AOI221X1 g7509__9867(.A0 (\fifo[8] [2]), .A1 (n_332), .B0
       (\fifo[9] [2]), .B1 (n_331), .C0 (n_136), .Y (n_333));
  SDFFQXL \fifo_reg[4][6] (.CK (clk_i), .D (n_280), .SI (rd_data_o[2]),
       .SE (scan_en), .Q (\fifo[4] [6]));
  SDFFQXL \fifo_reg[4][2] (.CK (clk_i), .D (n_285), .SI (\fifo[4] [6]),
       .SE (scan_en), .Q (\fifo[4] [2]));
  SDFFQXL \fifo_reg[4][3] (.CK (clk_i), .D (n_283), .SI (\fifo[4] [2]),
       .SE (scan_en), .Q (\fifo[4] [3]));
  SDFFQXL \fifo_reg[4][4] (.CK (clk_i), .D (n_290), .SI (\fifo[4] [3]),
       .SE (scan_en), .Q (\fifo[4] [4]));
  SDFFQXL \fifo_reg[4][5] (.CK (clk_i), .D (n_282), .SI (\fifo[4] [4]),
       .SE (scan_en), .Q (\fifo[4] [5]));
  SDFFQXL \fifo_reg[4][1] (.CK (clk_i), .D (n_295), .SI (\fifo[4] [5]),
       .SE (scan_en), .Q (\fifo[4] [1]));
  SDFFQXL \fifo_reg[4][7] (.CK (clk_i), .D (n_279), .SI (\fifo[4] [1]),
       .SE (scan_en), .Q (\fifo[4] [7]));
  SDFFQXL \fifo_reg[12][0] (.CK (clk_i), .D (n_271), .SI (\fifo[4]
       [7]), .SE (scan_en), .Q (\fifo[12] [0]));
  SDFFQXL \fifo_reg[12][1] (.CK (clk_i), .D (n_265), .SI (\fifo[12]
       [0]), .SE (scan_en), .Q (\fifo[12] [1]));
  SDFFQXL \fifo_reg[12][2] (.CK (clk_i), .D (n_264), .SI (\fifo[12]
       [1]), .SE (scan_en), .Q (\fifo[12] [2]));
  SDFFQXL \fifo_reg[4][0] (.CK (clk_i), .D (n_284), .SI (\fifo[12]
       [2]), .SE (scan_en), .Q (\fifo[4] [0]));
  SDFFQXL rd_toggle_flag_reg(.CK (clk_i), .D (n_303), .SI (\fifo[4]
       [0]), .SE (scan_en), .Q (rd_toggle_flag));
  SDFFQXL \fifo_reg[12][4] (.CK (clk_i), .D (n_262), .SI
       (rd_toggle_flag), .SE (scan_en), .Q (\fifo[12] [4]));
  SDFFQXL \fifo_reg[12][5] (.CK (clk_i), .D (n_261), .SI (\fifo[12]
       [4]), .SE (scan_en), .Q (\fifo[12] [5]));
  SDFFQXL \fifo_reg[12][6] (.CK (clk_i), .D (n_304), .SI (\fifo[12]
       [5]), .SE (scan_en), .Q (\fifo[12] [6]));
  SDFFQXL \fifo_reg[12][7] (.CK (clk_i), .D (n_294), .SI (\fifo[12]
       [6]), .SE (scan_en), .Q (\fifo[12] [7]));
  SDFFQXL \fifo_reg[8][1] (.CK (clk_i), .D (n_298), .SI (\fifo[12]
       [7]), .SE (scan_en), .Q (\fifo[8] [1]));
  SDFFQXL \fifo_reg[8][2] (.CK (clk_i), .D (n_302), .SI (\fifo[8] [1]),
       .SE (scan_en), .Q (\fifo[8] [2]));
  SDFFQXL \fifo_reg[8][3] (.CK (clk_i), .D (n_297), .SI (\fifo[8] [2]),
       .SE (scan_en), .Q (\fifo[8] [3]));
  SDFFQXL \fifo_reg[8][4] (.CK (clk_i), .D (n_296), .SI (\fifo[8] [3]),
       .SE (scan_en), .Q (\fifo[8] [4]));
  SDFFQXL \fifo_reg[8][5] (.CK (clk_i), .D (n_305), .SI (\fifo[8] [4]),
       .SE (scan_en), .Q (\fifo[8] [5]));
  SDFFQXL \fifo_reg[8][6] (.CK (clk_i), .D (n_287), .SI (\fifo[8] [5]),
       .SE (scan_en), .Q (\fifo[8] [6]));
  SDFFQXL \fifo_reg[8][7] (.CK (clk_i), .D (n_286), .SI (\fifo[8] [6]),
       .SE (scan_en), .Q (\fifo[8] [7]));
  SDFFQXL \fifo_reg[8][0] (.CK (clk_i), .D (n_299), .SI (\fifo[8] [7]),
       .SE (scan_en), .Q (\fifo[8] [0]));
  SDFFQXL \fifo_reg[12][3] (.CK (clk_i), .D (n_263), .SI (\fifo[8]
       [0]), .SE (scan_en), .Q (\fifo[12] [3]));
  AOI222X1 g7515__3377(.A0 (rd_data_o[4]), .A1 (n_328), .B0
       (\fifo[2] [4]), .B1 (n_325), .C0 (\fifo[15] [4]), .C1 (n_327),
       .Y (n_330));
  AOI222X1 g7516__9719(.A0 (rd_data_o[5]), .A1 (n_328), .B0
       (\fifo[0] [5]), .B1 (n_315), .C0 (\fifo[15] [5]), .C1 (n_327),
       .Y (n_329));
  AOI222X1 g7514__1591(.A0 (rd_data_o[3]), .A1 (n_328), .B0
       (\fifo[2] [3]), .B1 (n_325), .C0 (\fifo[15] [3]), .C1 (n_327),
       .Y (n_326));
  AOI222X1 g7513__6789(.A0 (\fifo[11] [2]), .A1 (n_320), .B0
       (\fifo[13] [2]), .B1 (n_319), .C0 (\fifo[15] [2]), .C1 (n_327),
       .Y (n_324));
  AOI222X1 g7512__5927(.A0 (rd_data_o[1]), .A1 (n_328), .B0
       (\fifo[2] [1]), .B1 (n_325), .C0 (\fifo[15] [1]), .C1 (n_327),
       .Y (n_323));
  AOI222X1 g7511__2001(.A0 (rd_data_o[0]), .A1 (n_328), .B0
       (\fifo[5] [0]), .B1 (n_306), .C0 (\fifo[15] [0]), .C1 (n_327),
       .Y (n_322));
  AOI222X1 g7510__1122(.A0 (\fifo[11] [7]), .A1 (n_320), .B0
       (\fifo[13] [7]), .B1 (n_319), .C0 (\fifo[15] [7]), .C1 (n_327),
       .Y (n_321));
  SDFFQXL \fifo_reg[11][4] (.CK (clk_i), .D (n_148), .SI (\fifo[12]
       [3]), .SE (scan_en), .Q (\fifo[11] [4]));
  SDFFQXL \fifo_reg[7][0] (.CK (clk_i), .D (n_223), .SI (\fifo[11]
       [4]), .SE (scan_en), .Q (\fifo[7] [0]));
  SDFFQXL \fifo_reg[10][3] (.CK (clk_i), .D (n_188), .SI (\fifo[7]
       [0]), .SE (scan_en), .Q (\fifo[10] [3]));
  SDFFQXL \fifo_reg[5][7] (.CK (clk_i), .D (n_174), .SI (\fifo[10]
       [3]), .SE (scan_en), .Q (\fifo[5] [7]));
  SDFFQXL \fifo_reg[1][6] (.CK (clk_i), .D (n_147), .SI (\fifo[5] [7]),
       .SE (scan_en), .Q (\fifo[1] [6]));
  SDFFQXL \fifo_reg[3][4] (.CK (clk_i), .D (n_198), .SI (\fifo[1] [6]),
       .SE (scan_en), .Q (\fifo[3] [4]));
  SDFFQXL \fifo_reg[14][2] (.CK (clk_i), .D (n_254), .SI (\fifo[3]
       [4]), .SE (scan_en), .Q (\fifo[14] [2]));
  SDFFQXL \fifo_reg[10][0] (.CK (clk_i), .D (n_176), .SI (\fifo[14]
       [2]), .SE (scan_en), .Q (\fifo[10] [0]));
  SDFFQXL \fifo_reg[1][3] (.CK (clk_i), .D (n_181), .SI (\fifo[10]
       [0]), .SE (scan_en), .Q (\fifo[1] [3]));
  SDFFQXL \fifo_reg[10][1] (.CK (clk_i), .D (n_199), .SI (\fifo[1]
       [3]), .SE (scan_en), .Q (\fifo[10] [1]));
  SDFFQXL \fifo_reg[10][2] (.CK (clk_i), .D (n_195), .SI (\fifo[10]
       [1]), .SE (scan_en), .Q (\fifo[10] [2]));
  SDFFQXL \fifo_reg[1][2] (.CK (clk_i), .D (n_179), .SI (\fifo[10]
       [2]), .SE (scan_en), .Q (\fifo[1] [2]));
  SDFFQXL \fifo_reg[10][4] (.CK (clk_i), .D (n_183), .SI (\fifo[1]
       [2]), .SE (scan_en), .Q (\fifo[10] [4]));
  SDFFQXL \fifo_reg[10][5] (.CK (clk_i), .D (n_178), .SI (\fifo[10]
       [4]), .SE (scan_en), .Q (\fifo[10] [5]));
  SDFFQXL \fifo_reg[1][4] (.CK (clk_i), .D (n_160), .SI (\fifo[10]
       [5]), .SE (scan_en), .Q (\fifo[1] [4]));
  SDFFQXL \fifo_reg[10][6] (.CK (clk_i), .D (n_175), .SI (\fifo[1]
       [4]), .SE (scan_en), .Q (\fifo[10] [6]));
  SDFFQXL \fifo_reg[0][4] (.CK (clk_i), .D (n_245), .SI
       (ts_pbuf_extsi148_), .SE (scan_en), .Q (\fifo[0] [4]));
  SDFFQXL \fifo_reg[13][6] (.CK (clk_i), .D (n_121), .SI (\fifo[0]
       [4]), .SE (scan_en), .Q (\fifo[13] [6]));
  SDFFQXL \fifo_reg[3][3] (.CK (clk_i), .D (n_200), .SI (\fifo[13]
       [6]), .SE (scan_en), .Q (\fifo[3] [3]));
  SDFFQXL \fifo_reg[11][0] (.CK (clk_i), .D (n_165), .SI (\fifo[3]
       [3]), .SE (scan_en), .Q (\fifo[11] [0]));
  SDFFQXL \fifo_reg[11][1] (.CK (clk_i), .D (n_163), .SI (\fifo[11]
       [0]), .SE (scan_en), .Q (\fifo[11] [1]));
  SDFFQXL \fifo_reg[11][2] (.CK (clk_i), .D (n_157), .SI (\fifo[11]
       [1]), .SE (scan_en), .Q (\fifo[11] [2]));
  SDFFQXL \fifo_reg[2][7] (.CK (clk_i), .D (n_260), .SI (\fifo[11]
       [2]), .SE (scan_en), .Q (\fifo[2] [7]));
  SDFFQXL \fifo_reg[1][5] (.CK (clk_i), .D (n_159), .SI (\fifo[2] [7]),
       .SE (scan_en), .Q (\fifo[1] [5]));
  SDFFQXL \fifo_reg[11][3] (.CK (clk_i), .D (n_149), .SI (\fifo[1]
       [5]), .SE (scan_en), .Q (\fifo[11] [3]));
  SDFFQXL \fifo_reg[14][6] (.CK (clk_i), .D (n_239), .SI (\fifo[11]
       [3]), .SE (scan_en), .Q (\fifo[14] [6]));
  SDFFQXL \fifo_reg[10][7] (.CK (clk_i), .D (n_172), .SI (\fifo[14]
       [6]), .SE (scan_en), .Q (\fifo[10] [7]));
  SDFFQXL \fifo_reg[11][5] (.CK (clk_i), .D (n_145), .SI (\fifo[10]
       [7]), .SE (scan_en), .Q (\fifo[11] [5]));
  SDFFQXL \fifo_reg[11][7] (.CK (clk_i), .D (n_138), .SI (\fifo[11]
       [5]), .SE (scan_en), .Q (\fifo[11] [7]));
  SDFFQXL \fifo_reg[5][0] (.CK (clk_i), .D (n_141), .SI (\fifo[11]
       [7]), .SE (scan_en), .Q (\fifo[5] [0]));
  SDFFQXL \fifo_reg[14][1] (.CK (clk_i), .D (n_113), .SI (\fifo[5]
       [0]), .SE (scan_en), .Q (\fifo[14] [1]));
  SDFFQXL \fifo_reg[5][1] (.CK (clk_i), .D (n_128), .SI (\fifo[14]
       [1]), .SE (scan_en), .Q (\fifo[5] [1]));
  SDFFQXL \fifo_reg[5][2] (.CK (clk_i), .D (n_126), .SI (\fifo[5] [1]),
       .SE (scan_en), .Q (\fifo[5] [2]));
  SDFFQXL \fifo_reg[1][7] (.CK (clk_i), .D (n_131), .SI (\fifo[5] [2]),
       .SE (scan_en), .Q (\fifo[1] [7]));
  SDFFQXL \fifo_reg[5][3] (.CK (clk_i), .D (n_125), .SI (\fifo[1] [7]),
       .SE (scan_en), .Q (\fifo[5] [3]));
  SDFFQXL \fifo_reg[0][1] (.CK (clk_i), .D (n_133), .SI (\fifo[5] [3]),
       .SE (scan_en), .Q (\fifo[0] [1]));
  SDFFQXL \fifo_reg[2][0] (.CK (clk_i), .D (n_233), .SI (\fifo[0] [1]),
       .SE (scan_en), .Q (\fifo[2] [0]));
  SDFFQXL \fifo_reg[5][4] (.CK (clk_i), .D (n_242), .SI (\fifo[2] [0]),
       .SE (scan_en), .Q (\fifo[5] [4]));
  SDFFQXL \fifo_reg[5][5] (.CK (clk_i), .D (n_255), .SI (\fifo[5] [4]),
       .SE (scan_en), .Q (\fifo[5] [5]));
  SDFFQXL \fifo_reg[13][0] (.CK (clk_i), .D (n_246), .SI (\fifo[5]
       [5]), .SE (scan_en), .Q (\fifo[13] [0]));
  SDFFQXL \fifo_reg[11][6] (.CK (clk_i), .D (n_142), .SI (\fifo[13]
       [0]), .SE (scan_en), .Q (\fifo[11] [6]));
  SDFFQXL \fifo_reg[13][2] (.CK (clk_i), .D (n_116), .SI (\fifo[11]
       [6]), .SE (scan_en), .Q (\fifo[13] [2]));
  SDFFQXL \fifo_reg[5][6] (.CK (clk_i), .D (n_120), .SI (\fifo[13]
       [2]), .SE (scan_en), .Q (\fifo[5] [6]));
  SDFFQXL \fifo_reg[13][3] (.CK (clk_i), .D (n_124), .SI (\fifo[5]
       [6]), .SE (scan_en), .Q (\fifo[13] [3]));
  SDFFQXL \fifo_reg[13][4] (.CK (clk_i), .D (n_123), .SI (\fifo[13]
       [3]), .SE (scan_en), .Q (\fifo[13] [4]));
  SDFFQXL \fifo_reg[13][5] (.CK (clk_i), .D (n_122), .SI (\fifo[13]
       [4]), .SE (scan_en), .Q (\fifo[13] [5]));
  SDFFQXL \fifo_reg[2][1] (.CK (clk_i), .D (n_117), .SI (\fifo[13]
       [5]), .SE (scan_en), .Q (\fifo[2] [1]));
  SDFFQXL \fifo_reg[13][7] (.CK (clk_i), .D (n_118), .SI (\fifo[2]
       [1]), .SE (scan_en), .Q (\fifo[13] [7]));
  SDFFQXL \fifo_reg[14][0] (.CK (clk_i), .D (n_115), .SI (\fifo[13]
       [7]), .SE (scan_en), .Q (\fifo[14] [0]));
  SDFFQXL \fifo_reg[6][0] (.CK (clk_i), .D (n_119), .SI (\fifo[14]
       [0]), .SE (scan_en), .Q (\fifo[6] [0]));
  SDFFQXL \fifo_reg[6][1] (.CK (clk_i), .D (n_256), .SI (\fifo[6] [0]),
       .SE (scan_en), .Q (\fifo[6] [1]));
  SDFFQXL \fifo_reg[0][0] (.CK (clk_i), .D (n_197), .SI (\fifo[6] [1]),
       .SE (scan_en), .Q (\fifo[0] [0]));
  SDFFQXL \fifo_reg[9][3] (.CK (clk_i), .D (n_185), .SI (\fifo[0] [0]),
       .SE (scan_en), .Q (\fifo[9] [3]));
  NAND4XL g7568__2005(.A (n_95), .B (n_97), .C (n_90), .D (n_91), .Y
       (n_318));
  NAND4XL g7638__9771(.A (n_86), .B (n_108), .C (n_96), .D (n_111), .Y
       (n_317));
  AOI221X1 g7647__3457(.A0 (\fifo[1] [0]), .A1 (n_110), .B0
       (\fifo[0] [0]), .B1 (n_315), .C0 (n_92), .Y (n_316));
  AOI221X1 g7648__1279(.A0 (\fifo[6] [1]), .A1 (n_101), .B0
       (\fifo[0] [1]), .B1 (n_315), .C0 (n_87), .Y (n_314));
  AOI221X1 g7649__6179(.A0 (\fifo[4] [3]), .A1 (n_311), .B0
       (\fifo[3] [3]), .B1 (n_310), .C0 (n_99), .Y (n_313));
  AOI221X1 g7650__7837(.A0 (\fifo[4] [4]), .A1 (n_311), .B0
       (\fifo[3] [4]), .B1 (n_310), .C0 (n_88), .Y (n_312));
  AOI221X1 g7651__7557(.A0 (\fifo[4] [5]), .A1 (n_311), .B0
       (\fifo[3] [5]), .B1 (n_310), .C0 (n_94), .Y (n_309));
  AOI221X1 g7652__7654(.A0 (\fifo[4] [6]), .A1 (n_311), .B0
       (\fifo[0] [6]), .B1 (n_315), .C0 (n_89), .Y (n_308));
  AOI222X1 g7517__8867(.A0 (rd_data_o[6]), .A1 (n_328), .B0
       (\fifo[5] [6]), .B1 (n_306), .C0 (\fifo[15] [6]), .C1 (n_327),
       .Y (n_307));
  SDFFQXL \fifo_reg[0][6] (.CK (clk_i), .D (n_206), .SI (\fifo[9] [3]),
       .SE (scan_en), .Q (\fifo[0] [6]));
  SDFFQXL \fifo_reg[2][5] (.CK (clk_i), .D (n_225), .SI (\fifo[0] [6]),
       .SE (scan_en), .Q (\fifo[2] [5]));
  SDFFQXL \fifo_reg[7][1] (.CK (clk_i), .D (n_222), .SI (\fifo[2] [5]),
       .SE (scan_en), .Q (\fifo[7] [1]));
  SDFFQXL \fifo_reg[2][6] (.CK (clk_i), .D (n_214), .SI (\fifo[7] [1]),
       .SE (scan_en), .Q (\fifo[2] [6]));
  SDFFQXL \fifo_reg[7][2] (.CK (clk_i), .D (n_219), .SI (\fifo[2] [6]),
       .SE (scan_en), .Q (\fifo[7] [2]));
  SDFFQXL \fifo_reg[13][1] (.CK (clk_i), .D (n_218), .SI (\fifo[7]
       [2]), .SE (scan_en), .Q (\fifo[13] [1]));
  SDFFQXL \fifo_reg[7][3] (.CK (clk_i), .D (n_215), .SI (\fifo[13]
       [1]), .SE (scan_en), .Q (\fifo[7] [3]));
  SDFFQXL \fifo_reg[7][4] (.CK (clk_i), .D (n_210), .SI (\fifo[7] [3]),
       .SE (scan_en), .Q (\fifo[7] [4]));
  SDFFQXL \fifo_reg[7][5] (.CK (clk_i), .D (n_209), .SI (\fifo[7] [4]),
       .SE (scan_en), .Q (\fifo[7] [5]));
  SDFFQXL \fifo_reg[0][5] (.CK (clk_i), .D (n_228), .SI (\fifo[7] [5]),
       .SE (scan_en), .Q (\fifo[0] [5]));
  SDFFQXL \fifo_reg[3][0] (.CK (clk_i), .D (n_213), .SI (\fifo[0] [5]),
       .SE (scan_en), .Q (\fifo[3] [0]));
  SDFFQXL \fifo_reg[7][6] (.CK (clk_i), .D (n_208), .SI (\fifo[3] [0]),
       .SE (scan_en), .Q (\fifo[7] [6]));
  SDFFQXL \fifo_reg[0][7] (.CK (clk_i), .D (n_224), .SI
       (ts_pbuf_extsi149_), .SE (scan_en), .Q (\fifo[0] [7]));
  SDFFQXL \fifo_reg[14][3] (.CK (clk_i), .D (n_253), .SI (\fifo[0]
       [7]), .SE (scan_en), .Q (\fifo[14] [3]));
  SDFFQXL \fifo_reg[3][1] (.CK (clk_i), .D (n_236), .SI (\fifo[14]
       [3]), .SE (scan_en), .Q (\fifo[3] [1]));
  SDFFQXL \fifo_reg[3][2] (.CK (clk_i), .D (n_205), .SI (\fifo[3] [1]),
       .SE (scan_en), .Q (\fifo[3] [2]));
  SDFFQXL \fifo_reg[9][1] (.CK (clk_i), .D (n_189), .SI (\fifo[3] [2]),
       .SE (scan_en), .Q (\fifo[9] [1]));
  SDFFQXL \fifo_reg[1][0] (.CK (clk_i), .D (n_238), .SI (\fifo[9] [1]),
       .SE (scan_en), .Q (\fifo[1] [0]));
  SDFFQXL \fifo_reg[3][5] (.CK (clk_i), .D (n_196), .SI (\fifo[1] [0]),
       .SE (scan_en), .Q (\fifo[3] [5]));
  SDFFQXL \fifo_reg[9][0] (.CK (clk_i), .D (n_192), .SI (\fifo[3] [5]),
       .SE (scan_en), .Q (\fifo[9] [0]));
  SDFFQXL \fifo_reg[3][6] (.CK (clk_i), .D (n_187), .SI (\fifo[9] [0]),
       .SE (scan_en), .Q (\fifo[3] [6]));
  SDFFQXL \fifo_reg[6][3] (.CK (clk_i), .D (n_243), .SI (\fifo[3] [6]),
       .SE (scan_en), .Q (\fifo[6] [3]));
  SDFFQXL \fifo_reg[9][2] (.CK (clk_i), .D (n_186), .SI (\fifo[6] [3]),
       .SE (scan_en), .Q (\fifo[9] [2]));
  SDFFQXL \fifo_reg[9][4] (.CK (clk_i), .D (n_182), .SI (\fifo[9] [2]),
       .SE (scan_en), .Q (\fifo[9] [4]));
  SDFFQXL \fifo_reg[3][7] (.CK (clk_i), .D (n_184), .SI (\fifo[9] [4]),
       .SE (scan_en), .Q (\fifo[3] [7]));
  SDFFQXL \fifo_reg[9][5] (.CK (clk_i), .D (n_180), .SI (\fifo[3] [7]),
       .SE (scan_en), .Q (\fifo[9] [5]));
  SDFFQXL \fifo_reg[0][2] (.CK (clk_i), .D (n_114), .SI (\fifo[9] [5]),
       .SE (scan_en), .Q (\fifo[0] [2]));
  SDFFQXL \fifo_reg[2][2] (.CK (clk_i), .D (n_259), .SI (\fifo[0] [2]),
       .SE (scan_en), .Q (\fifo[2] [2]));
  SDFFQXL \fifo_reg[9][7] (.CK (clk_i), .D (n_177), .SI (\fifo[2] [2]),
       .SE (scan_en), .Q (\fifo[9] [7]));
  SDFFQXL \fifo_reg[14][4] (.CK (clk_i), .D (n_247), .SI (\fifo[9]
       [7]), .SE (scan_en), .Q (\fifo[14] [4]));
  SDFFQXL \fifo_reg[6][2] (.CK (clk_i), .D (n_250), .SI (\fifo[14]
       [4]), .SE (scan_en), .Q (\fifo[6] [2]));
  SDFFQXL \fifo_reg[15][5] (.CK (clk_i), .D (n_173), .SI (\fifo[6]
       [2]), .SE (scan_en), .Q (\fifo[15] [5]));
  SDFFQXL \fifo_reg[15][1] (.CK (clk_i), .D (n_166), .SI (\fifo[15]
       [5]), .SE (scan_en), .Q (\fifo[15] [1]));
  SDFFQXL \fifo_reg[15][0] (.CK (clk_i), .D (n_158), .SI (\fifo[15]
       [1]), .SE (scan_en), .Q (\fifo[15] [0]));
  SDFFQXL \fifo_reg[15][6] (.CK (clk_i), .D (n_135), .SI (\fifo[15]
       [0]), .SE (scan_en), .Q (\fifo[15] [6]));
  SDFFQXL \fifo_reg[15][2] (.CK (clk_i), .D (n_167), .SI (\fifo[15]
       [6]), .SE (scan_en), .Q (\fifo[15] [2]));
  SDFFQXL \fifo_reg[15][4] (.CK (clk_i), .D (n_171), .SI (\fifo[15]
       [2]), .SE (scan_en), .Q (\fifo[15] [4]));
  SDFFQXL wr_toggle_flag_reg(.CK (clk_i), .D (n_164), .SI (\fifo[15]
       [4]), .SE (scan_en), .Q (wr_toggle_flag));
  SDFFQXL \fifo_reg[15][7] (.CK (clk_i), .D (n_150), .SI
       (wr_toggle_flag), .SE (scan_en), .Q (\fifo[15] [7]));
  SDFFQXL \fifo_reg[2][3] (.CK (clk_i), .D (n_237), .SI (\fifo[15]
       [7]), .SE (scan_en), .Q (\fifo[2] [3]));
  SDFFQXL \fifo_reg[14][7] (.CK (clk_i), .D (n_235), .SI (\fifo[2]
       [3]), .SE (scan_en), .Q (\fifo[14] [7]));
  SDFFQXL \fifo_reg[6][4] (.CK (clk_i), .D (n_234), .SI (\fifo[14]
       [7]), .SE (scan_en), .Q (\fifo[6] [4]));
  SDFFQXL \fifo_reg[0][3] (.CK (clk_i), .D (n_112), .SI (\fifo[6] [4]),
       .SE (scan_en), .Q (\fifo[0] [3]));
  SDFFQXL \fifo_reg[2][4] (.CK (clk_i), .D (n_232), .SI (\fifo[0] [3]),
       .SE (scan_en), .Q (\fifo[2] [4]));
  SDFFQXL \fifo_reg[6][5] (.CK (clk_i), .D (n_231), .SI (\fifo[2] [4]),
       .SE (scan_en), .Q (\fifo[6] [5]));
  SDFFQXL \fifo_reg[6][6] (.CK (clk_i), .D (n_230), .SI (\fifo[6] [5]),
       .SE (scan_en), .Q (\fifo[6] [6]));
  SDFFQXL \fifo_reg[1][1] (.CK (clk_i), .D (n_204), .SI (\fifo[6] [6]),
       .SE (scan_en), .Q (\fifo[1] [1]));
  SDFFQXL \fifo_reg[15][3] (.CK (clk_i), .D (n_168), .SI (\fifo[1]
       [1]), .SE (scan_en), .Q (\fifo[15] [3]));
  SDFFQXL \fifo_reg[14][5] (.CK (clk_i), .D (n_244), .SI (\fifo[15]
       [3]), .SE (scan_en), .Q (\fifo[14] [5]));
  SDFFQXL \fifo_reg[6][7] (.CK (clk_i), .D (n_229), .SI (\fifo[14]
       [5]), .SE (scan_en), .Q (\fifo[6] [7]));
  SDFFQXL \fifo_reg[9][6] (.CK (clk_i), .D (n_201), .SI (\fifo[6] [7]),
       .SE (scan_en), .Q (\fifo[9] [6]));
  SDFFQXL \fifo_reg[7][7] (.CK (clk_i), .D (n_207), .SI (\fifo[9] [6]),
       .SE (scan_en), .Q (\fifo[7] [7]));
  AO22XL g7618__1377(.A0 (\fifo[8] [5]), .A1 (n_301), .B0
       (wr_data_i[5]), .B1 (n_300), .Y (n_305));
  AO22XL g7505__3717(.A0 (\fifo[12] [6]), .A1 (n_293), .B0
       (wr_data_i[6]), .B1 (n_292), .Y (n_304));
  NOR2X1 g7507__4599(.A (rst_i), .B (n_107), .Y (n_303));
  AO22XL g7614__3779(.A0 (\fifo[8] [2]), .A1 (n_301), .B0
       (wr_data_i[2]), .B1 (n_300), .Y (n_302));
  AO22XL g7608__2007(.A0 (\fifo[8] [0]), .A1 (n_301), .B0
       (wr_data_i[0]), .B1 (n_300), .Y (n_299));
  AO22XL g7611__1237(.A0 (\fifo[8] [1]), .A1 (n_301), .B0
       (wr_data_i[1]), .B1 (n_300), .Y (n_298));
  AO22XL g7615__1297(.A0 (\fifo[8] [3]), .A1 (n_301), .B0
       (wr_data_i[3]), .B1 (n_300), .Y (n_297));
  AO22XL g7617__2006(.A0 (\fifo[8] [4]), .A1 (n_301), .B0
       (wr_data_i[4]), .B1 (n_300), .Y (n_296));
  AO22XL g7518__2833(.A0 (\fifo[4] [1]), .A1 (n_289), .B0
       (wr_data_i[1]), .B1 (n_288), .Y (n_295));
  AO22XL g7503__7547(.A0 (\fifo[12] [7]), .A1 (n_293), .B0
       (wr_data_i[7]), .B1 (n_292), .Y (n_294));
  AOI22XL g7640__7765(.A0 (\fifo[14] [6]), .A1 (n_277), .B0
       (\fifo[13] [6]), .B1 (n_319), .Y (n_291));
  AO22XL g7529__9867(.A0 (\fifo[4] [4]), .A1 (n_289), .B0
       (wr_data_i[4]), .B1 (n_288), .Y (n_290));
  AO22XL g7621__3377(.A0 (\fifo[8] [6]), .A1 (n_301), .B0
       (wr_data_i[6]), .B1 (n_300), .Y (n_287));
  AO22XL g7622__9719(.A0 (\fifo[8] [7]), .A1 (n_301), .B0
       (wr_data_i[7]), .B1 (n_300), .Y (n_286));
  AO22XL g7523__1591(.A0 (\fifo[4] [2]), .A1 (n_289), .B0
       (wr_data_i[2]), .B1 (n_288), .Y (n_285));
  AO22XL g7631__6789(.A0 (\fifo[4] [0]), .A1 (n_289), .B0
       (wr_data_i[0]), .B1 (n_288), .Y (n_284));
  AO22XL g7526__5927(.A0 (\fifo[4] [3]), .A1 (n_289), .B0
       (wr_data_i[3]), .B1 (n_288), .Y (n_283));
  SDFFHQX1 \rd_ptr_reg[3] (.CK (clk_i), .D (n_106), .SI (\fifo[7] [7]),
       .SE (scan_en), .Q (rd_ptr[3]));
  SDFFHQX1 \rd_ptr_reg[2] (.CK (clk_i), .D (n_105), .SI (rd_ptr[3]),
       .SE (scan_en), .Q (rd_ptr[2]));
  AO22XL g7532__2001(.A0 (\fifo[4] [5]), .A1 (n_289), .B0
       (wr_data_i[5]), .B1 (n_288), .Y (n_282));
  AOI22XL g7655__1122(.A0 (\fifo[12] [6]), .A1 (n_275), .B0
       (\fifo[11] [6]), .B1 (n_320), .Y (n_281));
  AO22XL g7537__2005(.A0 (\fifo[4] [6]), .A1 (n_289), .B0
       (wr_data_i[6]), .B1 (n_288), .Y (n_280));
  AO22XL g7541__9771(.A0 (\fifo[4] [7]), .A1 (n_289), .B0
       (wr_data_i[7]), .B1 (n_288), .Y (n_279));
  AOI22XL g7667__3457(.A0 (\fifo[14] [0]), .A1 (n_277), .B0
       (\fifo[13] [0]), .B1 (n_319), .Y (n_278));
  AOI22XL g7669__1279(.A0 (\fifo[12] [0]), .A1 (n_275), .B0
       (\fifo[11] [0]), .B1 (n_320), .Y (n_276));
  AOI22XL g7671__6179(.A0 (\fifo[14] [1]), .A1 (n_277), .B0
       (\fifo[11] [1]), .B1 (n_320), .Y (n_274));
  AOI22XL g7672__7837(.A0 (\fifo[12] [1]), .A1 (n_275), .B0
       (\fifo[13] [1]), .B1 (n_319), .Y (n_273));
  AOI22XL g7677__7557(.A0 (\fifo[12] [4]), .A1 (n_275), .B0
       (\fifo[11] [4]), .B1 (n_320), .Y (n_272));
  AO22XL g7546__7654(.A0 (\fifo[12] [0]), .A1 (n_293), .B0
       (wr_data_i[0]), .B1 (n_292), .Y (n_271));
  AOI22XL g7678__8867(.A0 (\fifo[14] [3]), .A1 (n_277), .B0
       (\fifo[13] [3]), .B1 (n_319), .Y (n_270));
  AOI22XL g7680__1377(.A0 (\fifo[12] [3]), .A1 (n_275), .B0
       (\fifo[11] [3]), .B1 (n_320), .Y (n_269));
  AOI22XL g7682__3717(.A0 (\fifo[14] [4]), .A1 (n_277), .B0
       (\fifo[13] [4]), .B1 (n_319), .Y (n_268));
  AOI22XL g7685__4599(.A0 (\fifo[14] [5]), .A1 (n_277), .B0
       (\fifo[13] [5]), .B1 (n_319), .Y (n_267));
  AOI22XL g7687__3779(.A0 (\fifo[12] [5]), .A1 (n_275), .B0
       (\fifo[11] [5]), .B1 (n_320), .Y (n_266));
  AO22XL g7550__2007(.A0 (\fifo[12] [1]), .A1 (n_293), .B0
       (wr_data_i[1]), .B1 (n_292), .Y (n_265));
  AO22XL g7551__1237(.A0 (\fifo[12] [2]), .A1 (n_293), .B0
       (wr_data_i[2]), .B1 (n_292), .Y (n_264));
  AO22XL g7553__1297(.A0 (\fifo[12] [3]), .A1 (n_293), .B0
       (wr_data_i[3]), .B1 (n_292), .Y (n_263));
  AO22XL g7554__2006(.A0 (\fifo[12] [4]), .A1 (n_293), .B0
       (wr_data_i[4]), .B1 (n_292), .Y (n_262));
  AO22XL g7556__2833(.A0 (\fifo[12] [5]), .A1 (n_293), .B0
       (wr_data_i[5]), .B1 (n_292), .Y (n_261));
  AO22XL g7600__7547(.A0 (\fifo[2] [7]), .A1 (n_258), .B0
       (wr_data_i[7]), .B1 (n_257), .Y (n_260));
  AO22XL g7578__7765(.A0 (\fifo[2] [2]), .A1 (n_258), .B0
       (wr_data_i[2]), .B1 (n_257), .Y (n_259));
  AO22XL g7579__9867(.A0 (\fifo[6] [1]), .A1 (n_249), .B0
       (wr_data_i[1]), .B1 (n_248), .Y (n_256));
  AO22XL g7501__3377(.A0 (\fifo[5] [5]), .A1 (n_241), .B0
       (wr_data_i[5]), .B1 (n_364), .Y (n_255));
  AO22XL g7580__9719(.A0 (\fifo[14] [2]), .A1 (n_252), .B0
       (wr_data_i[2]), .B1 (n_251), .Y (n_254));
  AO22XL g7581__1591(.A0 (\fifo[14] [3]), .A1 (n_252), .B0
       (wr_data_i[3]), .B1 (n_251), .Y (n_253));
  AO22XL g7582__6789(.A0 (\fifo[6] [2]), .A1 (n_249), .B0
       (wr_data_i[2]), .B1 (n_248), .Y (n_250));
  AO22XL g7583__5927(.A0 (\fifo[14] [4]), .A1 (n_252), .B0
       (wr_data_i[4]), .B1 (n_251), .Y (n_247));
  AO22XL g7502__2001(.A0 (\fifo[13] [0]), .A1 (n_217), .B0
       (wr_data_i[0]), .B1 (n_216), .Y (n_246));
  AO22XL g7584__1122(.A0 (\fifo[0] [4]), .A1 (n_227), .B0
       (wr_data_i[4]), .B1 (n_226), .Y (n_245));
  AO22XL g7585__2005(.A0 (\fifo[14] [5]), .A1 (n_252), .B0
       (wr_data_i[5]), .B1 (n_251), .Y (n_244));
  AO22XL g7586__9771(.A0 (\fifo[6] [3]), .A1 (n_249), .B0
       (wr_data_i[3]), .B1 (n_248), .Y (n_243));
  AO22XL g7504__3457(.A0 (\fifo[5] [4]), .A1 (n_241), .B0
       (wr_data_i[4]), .B1 (n_364), .Y (n_242));
  AO22XL g7587__1279(.A0 (\fifo[14] [6]), .A1 (n_252), .B0
       (wr_data_i[6]), .B1 (n_251), .Y (n_239));
  AO22XL g7616__6179(.A0 (\fifo[1] [0]), .A1 (n_203), .B0
       (wr_data_i[0]), .B1 (n_202), .Y (n_238));
  AO22XL g7588__7837(.A0 (\fifo[2] [3]), .A1 (n_258), .B0
       (wr_data_i[3]), .B1 (n_257), .Y (n_237));
  AO22XL g7610__7557(.A0 (\fifo[3] [1]), .A1 (n_212), .B0
       (wr_data_i[1]), .B1 (n_362), .Y (n_236));
  AO22XL g7589__7654(.A0 (\fifo[14] [7]), .A1 (n_252), .B0
       (wr_data_i[7]), .B1 (n_251), .Y (n_235));
  AO22XL g7590__8867(.A0 (\fifo[6] [4]), .A1 (n_249), .B0
       (wr_data_i[4]), .B1 (n_248), .Y (n_234));
  AO22XL g7506__1377(.A0 (\fifo[2] [0]), .A1 (n_258), .B0
       (wr_data_i[0]), .B1 (n_257), .Y (n_233));
  AO22XL g7591__3717(.A0 (\fifo[2] [4]), .A1 (n_258), .B0
       (wr_data_i[4]), .B1 (n_257), .Y (n_232));
  AO22XL g7592__4599(.A0 (\fifo[6] [5]), .A1 (n_249), .B0
       (wr_data_i[5]), .B1 (n_248), .Y (n_231));
  AO22XL g7593__3779(.A0 (\fifo[6] [6]), .A1 (n_249), .B0
       (wr_data_i[6]), .B1 (n_248), .Y (n_230));
  AO22XL g7594__2007(.A0 (\fifo[6] [7]), .A1 (n_249), .B0
       (wr_data_i[7]), .B1 (n_248), .Y (n_229));
  AO22XL g7595__1237(.A0 (\fifo[0] [5]), .A1 (n_227), .B0
       (wr_data_i[5]), .B1 (n_226), .Y (n_228));
  AO22XL g7596__1297(.A0 (\fifo[2] [5]), .A1 (n_258), .B0
       (wr_data_i[5]), .B1 (n_257), .Y (n_225));
  AO22XL g7609__2006(.A0 (\fifo[0] [7]), .A1 (n_227), .B0
       (wr_data_i[7]), .B1 (n_226), .Y (n_224));
  AO22XL g7597__2833(.A0 (\fifo[7] [0]), .A1 (n_221), .B0
       (wr_data_i[0]), .B1 (n_220), .Y (n_223));
  AO22XL g7598__7547(.A0 (\fifo[7] [1]), .A1 (n_221), .B0
       (wr_data_i[1]), .B1 (n_220), .Y (n_222));
  AO22XL g7599__7765(.A0 (\fifo[7] [2]), .A1 (n_221), .B0
       (wr_data_i[2]), .B1 (n_220), .Y (n_219));
  AO22XL g7500__9867(.A0 (\fifo[13] [1]), .A1 (n_217), .B0
       (wr_data_i[1]), .B1 (n_216), .Y (n_218));
  AO22XL g7601__3377(.A0 (\fifo[7] [3]), .A1 (n_221), .B0
       (wr_data_i[3]), .B1 (n_220), .Y (n_215));
  AO22XL g7602__9719(.A0 (\fifo[2] [6]), .A1 (n_258), .B0
       (wr_data_i[6]), .B1 (n_257), .Y (n_214));
  AO22XL g7603__1591(.A0 (\fifo[3] [0]), .A1 (n_212), .B0
       (wr_data_i[0]), .B1 (n_362), .Y (n_213));
  AO22XL g7604__6789(.A0 (\fifo[7] [4]), .A1 (n_221), .B0
       (wr_data_i[4]), .B1 (n_220), .Y (n_210));
  AO22XL g7605__5927(.A0 (\fifo[7] [5]), .A1 (n_221), .B0
       (wr_data_i[5]), .B1 (n_220), .Y (n_209));
  AO22XL g7606__2001(.A0 (\fifo[7] [6]), .A1 (n_221), .B0
       (wr_data_i[6]), .B1 (n_220), .Y (n_208));
  AO22XL g7607__1122(.A0 (\fifo[7] [7]), .A1 (n_221), .B0
       (wr_data_i[7]), .B1 (n_220), .Y (n_207));
  AO22XL g7612__2005(.A0 (\fifo[0] [6]), .A1 (n_227), .B0
       (wr_data_i[6]), .B1 (n_226), .Y (n_206));
  AO22XL g7613__9771(.A0 (\fifo[3] [2]), .A1 (n_212), .B0
       (wr_data_i[2]), .B1 (n_362), .Y (n_205));
  AO22XL g7634__3457(.A0 (\fifo[1] [1]), .A1 (n_203), .B0
       (wr_data_i[1]), .B1 (n_202), .Y (n_204));
  AO22XL g7633__1279(.A0 (\fifo[9] [6]), .A1 (n_191), .B0
       (wr_data_i[6]), .B1 (n_190), .Y (n_201));
  AO22XL g7619__6179(.A0 (\fifo[3] [3]), .A1 (n_212), .B0
       (wr_data_i[3]), .B1 (n_362), .Y (n_200));
  AO22XL g7519__7837(.A0 (\fifo[10] [1]), .A1 (n_194), .B0
       (wr_data_i[1]), .B1 (n_193), .Y (n_199));
  AO22XL g7620__7557(.A0 (\fifo[3] [4]), .A1 (n_212), .B0
       (wr_data_i[4]), .B1 (n_362), .Y (n_198));
  AO22XL g7520__7654(.A0 (\fifo[0] [0]), .A1 (n_227), .B0
       (wr_data_i[0]), .B1 (n_226), .Y (n_197));
  AO22XL g7623__8867(.A0 (\fifo[3] [5]), .A1 (n_212), .B0
       (wr_data_i[5]), .B1 (n_362), .Y (n_196));
  AO22XL g7521__1377(.A0 (\fifo[10] [2]), .A1 (n_194), .B0
       (wr_data_i[2]), .B1 (n_193), .Y (n_195));
  AO22XL g7624__3717(.A0 (\fifo[9] [0]), .A1 (n_191), .B0
       (wr_data_i[0]), .B1 (n_190), .Y (n_192));
  AO22XL g7625__4599(.A0 (\fifo[9] [1]), .A1 (n_191), .B0
       (wr_data_i[1]), .B1 (n_190), .Y (n_189));
  AO22XL g7522__3779(.A0 (\fifo[10] [3]), .A1 (n_194), .B0
       (wr_data_i[3]), .B1 (n_193), .Y (n_188));
  AO22XL g7626__2007(.A0 (\fifo[3] [6]), .A1 (n_212), .B0
       (wr_data_i[6]), .B1 (n_362), .Y (n_187));
  AO22XL g7627__1237(.A0 (\fifo[9] [2]), .A1 (n_191), .B0
       (wr_data_i[2]), .B1 (n_190), .Y (n_186));
  AO22XL g7628__1297(.A0 (\fifo[9] [3]), .A1 (n_191), .B0
       (wr_data_i[3]), .B1 (n_190), .Y (n_185));
  AO22XL g7629__2006(.A0 (\fifo[3] [7]), .A1 (n_212), .B0
       (wr_data_i[7]), .B1 (n_362), .Y (n_184));
  AO22XL g7524__2833(.A0 (\fifo[10] [4]), .A1 (n_194), .B0
       (wr_data_i[4]), .B1 (n_193), .Y (n_183));
  AO22XL g7630__7547(.A0 (\fifo[9] [4]), .A1 (n_191), .B0
       (wr_data_i[4]), .B1 (n_190), .Y (n_182));
  AO22XL g7525__7765(.A0 (\fifo[1] [3]), .A1 (n_203), .B0
       (wr_data_i[3]), .B1 (n_202), .Y (n_181));
  AO22XL g7632__9867(.A0 (\fifo[9] [5]), .A1 (n_191), .B0
       (wr_data_i[5]), .B1 (n_190), .Y (n_180));
  SDFFHQX1 \rd_ptr_reg[1] (.CK (clk_i), .D (n_82), .SI (rd_ptr[2]), .SE
       (scan_en), .Q (rd_ptr[1]));
  SDFFHQX1 \rd_ptr_reg[0] (.CK (clk_i), .D (n_81), .SI (rd_ptr[1]), .SE
       (scan_en), .Q (rd_ptr[0]));
  AO22XL g7635__3377(.A0 (\fifo[1] [2]), .A1 (n_203), .B0
       (wr_data_i[2]), .B1 (n_202), .Y (n_179));
  AO22XL g7527__9719(.A0 (\fifo[10] [5]), .A1 (n_194), .B0
       (wr_data_i[5]), .B1 (n_193), .Y (n_178));
  AO22XL g7636__1591(.A0 (\fifo[9] [7]), .A1 (n_191), .B0
       (wr_data_i[7]), .B1 (n_190), .Y (n_177));
  AO22XL g7637__6789(.A0 (\fifo[10] [0]), .A1 (n_194), .B0
       (wr_data_i[0]), .B1 (n_193), .Y (n_176));
  AO22XL g7528__5927(.A0 (\fifo[10] [6]), .A1 (n_194), .B0
       (wr_data_i[6]), .B1 (n_193), .Y (n_175));
  AO22XL g7639__2001(.A0 (\fifo[5] [7]), .A1 (n_241), .B0
       (wr_data_i[7]), .B1 (n_364), .Y (n_174));
  AO22XL g7641__1122(.A0 (wr_data_i[5]), .A1 (n_170), .B0 (\fifo[15]
       [5]), .B1 (n_169), .Y (n_173));
  AO22XL g7530__2005(.A0 (\fifo[10] [7]), .A1 (n_194), .B0
       (wr_data_i[7]), .B1 (n_193), .Y (n_172));
  AO22XL g7642__9771(.A0 (wr_data_i[4]), .A1 (n_170), .B0 (\fifo[15]
       [4]), .B1 (n_169), .Y (n_171));
  AO22XL g7643__3457(.A0 (wr_data_i[3]), .A1 (n_170), .B0 (\fifo[15]
       [3]), .B1 (n_169), .Y (n_168));
  AO22XL g7644__1279(.A0 (wr_data_i[2]), .A1 (n_170), .B0 (\fifo[15]
       [2]), .B1 (n_169), .Y (n_167));
  AO22XL g7645__6179(.A0 (wr_data_i[1]), .A1 (n_170), .B0 (\fifo[15]
       [1]), .B1 (n_169), .Y (n_166));
  AO22XL g7531__7837(.A0 (\fifo[11] [0]), .A1 (n_162), .B0
       (wr_data_i[0]), .B1 (n_161), .Y (n_165));
  NOR2X1 g7646__7557(.A (rst_i), .B (n_84), .Y (n_164));
  AO22XL g7533__7654(.A0 (\fifo[11] [1]), .A1 (n_162), .B0
       (wr_data_i[1]), .B1 (n_161), .Y (n_163));
  AO22XL g7534__8867(.A0 (\fifo[1] [4]), .A1 (n_203), .B0
       (wr_data_i[4]), .B1 (n_202), .Y (n_160));
  AO22XL g7535__1377(.A0 (\fifo[1] [5]), .A1 (n_203), .B0
       (wr_data_i[5]), .B1 (n_202), .Y (n_159));
  AO22XL g7653__3717(.A0 (wr_data_i[0]), .A1 (n_170), .B0 (\fifo[15]
       [0]), .B1 (n_169), .Y (n_158));
  AO22XL g7536__4599(.A0 (\fifo[11] [2]), .A1 (n_162), .B0
       (wr_data_i[2]), .B1 (n_161), .Y (n_157));
  AOI22XL g7654__3779(.A0 (\fifo[8] [6]), .A1 (n_332), .B0 (\fifo[7]
       [6]), .B1 (n_153), .Y (n_156));
  AOI22XL g7656__2007(.A0 (\fifo[10] [6]), .A1 (n_151), .B0
       (\fifo[9] [6]), .B1 (n_331), .Y (n_155));
  AOI22X1 g7657__1237(.A0 (\fifo[12] [7]), .A1 (n_275), .B0
       (\fifo[7] [7]), .B1 (n_153), .Y (n_154));
  AO22XL g7658__1297(.A0 (\fifo[10] [7]), .A1 (n_151), .B0
       (\fifo[14] [7]), .B1 (n_277), .Y (n_152));
  AO22XL g7659__2006(.A0 (wr_data_i[7]), .A1 (n_170), .B0 (\fifo[15]
       [7]), .B1 (n_169), .Y (n_150));
  AO22XL g7538__2833(.A0 (\fifo[11] [3]), .A1 (n_162), .B0
       (wr_data_i[3]), .B1 (n_161), .Y (n_149));
  AO22XL g7539__7547(.A0 (\fifo[11] [4]), .A1 (n_162), .B0
       (wr_data_i[4]), .B1 (n_161), .Y (n_148));
  AO22XL g7540__7765(.A0 (\fifo[1] [6]), .A1 (n_203), .B0
       (wr_data_i[6]), .B1 (n_202), .Y (n_147));
  AOI22XL g7666__9867(.A0 (\fifo[10] [3]), .A1 (n_151), .B0
       (\fifo[9] [3]), .B1 (n_331), .Y (n_146));
  AO22XL g7542__3377(.A0 (\fifo[11] [5]), .A1 (n_162), .B0
       (wr_data_i[5]), .B1 (n_161), .Y (n_145));
  AOI22XL g7668__9719(.A0 (\fifo[8] [0]), .A1 (n_332), .B0 (\fifo[7]
       [0]), .B1 (n_153), .Y (n_144));
  AOI22XL g7670__1591(.A0 (\fifo[10] [0]), .A1 (n_151), .B0
       (\fifo[9] [0]), .B1 (n_331), .Y (n_143));
  AO22XL g7543__6789(.A0 (\fifo[11] [6]), .A1 (n_162), .B0
       (wr_data_i[6]), .B1 (n_161), .Y (n_142));
  AO22XL g7544__5927(.A0 (\fifo[5] [0]), .A1 (n_241), .B0
       (wr_data_i[0]), .B1 (n_364), .Y (n_141));
  AOI22XL g7673__2001(.A0 (\fifo[10] [1]), .A1 (n_151), .B0
       (\fifo[9] [1]), .B1 (n_331), .Y (n_140));
  AOI22XL g7674__1122(.A0 (\fifo[8] [1]), .A1 (n_332), .B0 (\fifo[7]
       [1]), .B1 (n_153), .Y (n_139));
  AO22XL g7545__2005(.A0 (\fifo[11] [7]), .A1 (n_162), .B0
       (wr_data_i[7]), .B1 (n_161), .Y (n_138));
  AOI22X1 g7675__9771(.A0 (\fifo[12] [2]), .A1 (n_275), .B0
       (\fifo[7] [2]), .B1 (n_153), .Y (n_137));
  AO22XL g7676__3457(.A0 (\fifo[10] [2]), .A1 (n_151), .B0
       (\fifo[14] [2]), .B1 (n_277), .Y (n_136));
  AO22XL g7679__1279(.A0 (wr_data_i[6]), .A1 (n_170), .B0 (\fifo[15]
       [6]), .B1 (n_169), .Y (n_135));
  AOI22XL g7681__6179(.A0 (\fifo[8] [3]), .A1 (n_332), .B0 (\fifo[7]
       [3]), .B1 (n_153), .Y (n_134));
  AO22XL g7547__7837(.A0 (\fifo[0] [1]), .A1 (n_227), .B0
       (wr_data_i[1]), .B1 (n_226), .Y (n_133));
  AOI22XL g7683__7557(.A0 (\fifo[8] [4]), .A1 (n_332), .B0 (\fifo[7]
       [4]), .B1 (n_153), .Y (n_132));
  AO22XL g7548__7654(.A0 (\fifo[1] [7]), .A1 (n_203), .B0
       (wr_data_i[7]), .B1 (n_202), .Y (n_131));
  AOI22XL g7684__8867(.A0 (\fifo[10] [4]), .A1 (n_151), .B0
       (\fifo[9] [4]), .B1 (n_331), .Y (n_130));
  AOI22XL g7686__1377(.A0 (\fifo[8] [5]), .A1 (n_332), .B0 (\fifo[7]
       [5]), .B1 (n_153), .Y (n_129));
  AO22XL g7549__3717(.A0 (\fifo[5] [1]), .A1 (n_241), .B0
       (wr_data_i[1]), .B1 (n_364), .Y (n_128));
  AOI22XL g7688__4599(.A0 (\fifo[10] [5]), .A1 (n_151), .B0
       (\fifo[9] [5]), .B1 (n_331), .Y (n_127));
  AO22XL g7552__3779(.A0 (\fifo[5] [2]), .A1 (n_241), .B0
       (wr_data_i[2]), .B1 (n_364), .Y (n_126));
  AO22XL g7555__2007(.A0 (\fifo[5] [3]), .A1 (n_241), .B0
       (wr_data_i[3]), .B1 (n_364), .Y (n_125));
  AO22XL g7496__1237(.A0 (\fifo[13] [3]), .A1 (n_217), .B0
       (wr_data_i[3]), .B1 (n_216), .Y (n_124));
  AO22XL g7569__1297(.A0 (\fifo[13] [4]), .A1 (n_217), .B0
       (wr_data_i[4]), .B1 (n_216), .Y (n_123));
  AO22XL g7570__2006(.A0 (\fifo[13] [5]), .A1 (n_217), .B0
       (wr_data_i[5]), .B1 (n_216), .Y (n_122));
  AO22XL g7571__2833(.A0 (\fifo[13] [6]), .A1 (n_217), .B0
       (wr_data_i[6]), .B1 (n_216), .Y (n_121));
  AO22XL g7497__7547(.A0 (\fifo[5] [6]), .A1 (n_241), .B0
       (wr_data_i[6]), .B1 (n_364), .Y (n_120));
  AO22XL g7572__7765(.A0 (\fifo[6] [0]), .A1 (n_249), .B0
       (wr_data_i[0]), .B1 (n_248), .Y (n_119));
  AO22XL g7573__9867(.A0 (\fifo[13] [7]), .A1 (n_217), .B0
       (wr_data_i[7]), .B1 (n_216), .Y (n_118));
  AO22XL g7574__3377(.A0 (\fifo[2] [1]), .A1 (n_258), .B0
       (wr_data_i[1]), .B1 (n_257), .Y (n_117));
  AO22XL g7498__9719(.A0 (\fifo[13] [2]), .A1 (n_217), .B0
       (wr_data_i[2]), .B1 (n_216), .Y (n_116));
  AO22XL g7575__1591(.A0 (\fifo[14] [0]), .A1 (n_252), .B0
       (wr_data_i[0]), .B1 (n_251), .Y (n_115));
  AO22XL g7499__6789(.A0 (\fifo[0] [2]), .A1 (n_227), .B0
       (wr_data_i[2]), .B1 (n_226), .Y (n_114));
  AO22XL g7576__5927(.A0 (\fifo[14] [1]), .A1 (n_252), .B0
       (wr_data_i[1]), .B1 (n_251), .Y (n_113));
  AO22XL g7577__2001(.A0 (\fifo[0] [3]), .A1 (n_227), .B0
       (wr_data_i[3]), .B1 (n_226), .Y (n_112));
  AOI22XL g7725__1122(.A0 (\fifo[1] [7]), .A1 (n_110), .B0 (\fifo[5]
       [7]), .B1 (n_306), .Y (n_111));
  AOI22X1 g7727__2005(.A0 (\fifo[0] [4]), .A1 (n_315), .B0 (\fifo[1]
       [4]), .B1 (n_110), .Y (n_109));
  AOI22XL g7726__9771(.A0 (\fifo[2] [7]), .A1 (n_325), .B0 (\fifo[4]
       [7]), .B1 (n_311), .Y (n_108));
  XNOR2X1 g7689__3457(.A (rd_toggle_flag), .B (n_55), .Y (n_107));
  OAI22X1 g7690__1279(.A0 (n_33), .A1 (n_103), .B0 (n_17), .B1 (n_104),
       .Y (n_106));
  OAI32X1 g7691__6179(.A0 (rd_ptr[2]), .A1 (n_54), .A2 (n_104), .B0
       (n_5), .B1 (n_103), .Y (n_105));
  AOI22X1 g7723__7837(.A0 (\fifo[2] [6]), .A1 (n_325), .B0 (\fifo[6]
       [6]), .B1 (n_101), .Y (n_102));
  AOI22X1 g7724__7557(.A0 (\fifo[2] [5]), .A1 (n_325), .B0 (\fifo[1]
       [5]), .B1 (n_110), .Y (n_100));
  AO22XL g7728__7654(.A0 (\fifo[6] [3]), .A1 (n_101), .B0 (\fifo[5]
       [3]), .B1 (n_306), .Y (n_99));
  SDFFHQX1 \wr_ptr_reg[0] (.CK (clk_i), .D (n_67), .SI (rd_ptr[0]), .SE
       (scan_en), .Q (wr_ptr[0]));
  SDFFHQX1 \wr_ptr_reg[1] (.CK (clk_i), .D (n_77), .SI (wr_ptr[0]), .SE
       (scan_en), .Q (wr_ptr[1]));
  SDFFHQX1 \wr_ptr_reg[3] (.CK (clk_i), .D (n_78), .SI (wr_ptr[1]), .SE
       (scan_en), .Q (wr_ptr[3]));
  SDFFHQX1 \wr_ptr_reg[2] (.CK (clk_i), .D (n_76), .SI (wr_ptr[3]), .SE
       (scan_en), .Q (wr_ptr[2]));
  AOI22X1 g7742__8867(.A0 (\fifo[1] [1]), .A1 (n_110), .B0 (\fifo[3]
       [1]), .B1 (n_310), .Y (n_98));
  AOI22XL g7730__1377(.A0 (\fifo[6] [2]), .A1 (n_101), .B0 (\fifo[5]
       [2]), .B1 (n_306), .Y (n_97));
  AOI22XL g7731__3717(.A0 (\fifo[0] [7]), .A1 (n_315), .B0 (\fifo[3]
       [7]), .B1 (n_310), .Y (n_96));
  AOI22XL g7732__4599(.A0 (\fifo[0] [2]), .A1 (n_315), .B0
       (rd_data_o[2]), .B1 (n_328), .Y (n_95));
  AO22XL g7733__3779(.A0 (\fifo[6] [5]), .A1 (n_101), .B0 (\fifo[5]
       [5]), .B1 (n_306), .Y (n_94));
  AOI22X1 g7734__2007(.A0 (\fifo[6] [0]), .A1 (n_101), .B0 (\fifo[3]
       [0]), .B1 (n_310), .Y (n_93));
  AO22XL g7735__1237(.A0 (\fifo[2] [0]), .A1 (n_325), .B0 (\fifo[4]
       [0]), .B1 (n_311), .Y (n_92));
  AOI22XL g7736__1297(.A0 (\fifo[2] [2]), .A1 (n_325), .B0 (\fifo[1]
       [2]), .B1 (n_110), .Y (n_91));
  AOI22XL g7737__2006(.A0 (\fifo[4] [2]), .A1 (n_311), .B0 (\fifo[3]
       [2]), .B1 (n_310), .Y (n_90));
  AO22XL g7738__2833(.A0 (\fifo[1] [6]), .A1 (n_110), .B0 (\fifo[3]
       [6]), .B1 (n_310), .Y (n_89));
  AO22XL g7739__7547(.A0 (\fifo[6] [4]), .A1 (n_101), .B0 (\fifo[5]
       [4]), .B1 (n_306), .Y (n_88));
  AO22XL g7740__7765(.A0 (\fifo[4] [1]), .A1 (n_311), .B0 (\fifo[5]
       [1]), .B1 (n_306), .Y (n_87));
  AOI22XL g7741__9867(.A0 (\fifo[6] [7]), .A1 (n_101), .B0
       (rd_data_o[7]), .B1 (n_328), .Y (n_86));
  AOI22X1 g7729__3377(.A0 (\fifo[0] [3]), .A1 (n_315), .B0 (\fifo[1]
       [3]), .B1 (n_110), .Y (n_85));
  XNOR2X1 g7719__9719(.A (wr_toggle_flag), .B (n_56), .Y (n_84));
  NOR2X1 g7716__1591(.A (n_69), .B (n_83), .Y (n_288));
  NOR2X1 g7743__6789(.A (n_73), .B (n_83), .Y (n_300));
  NOR2X1 g7717__5927(.A (n_65), .B (n_83), .Y (n_292));
  OAI22X1 g7722__2001(.A0 (n_0), .A1 (n_104), .B0 (n_6), .B1 (n_80), .Y
       (n_82));
  OAI22X1 g7721__1122(.A0 (rd_ptr[0]), .A1 (n_104), .B0 (n_37), .B1
       (n_80), .Y (n_81));
  NOR2X1 g7751__2005(.A (n_79), .B (n_62), .Y (n_327));
  NOR2X1 g7756__9771(.A (n_79), .B (n_57), .Y (n_319));
  NOR2X1 g7757__3457(.A (n_79), .B (n_59), .Y (n_320));
  NOR2X1 g7693__1279(.A (rst_i), .B (n_47), .Y (n_78));
  NOR2X1 g7694__6179(.A (rst_i), .B (n_38), .Y (n_77));
  NOR2X1 g7695__7837(.A (rst_i), .B (n_39), .Y (n_76));
  AND2X1 g7698__7557(.A (n_50), .B (n_74), .Y (n_226));
  NAND2X1 g7703__7654(.A (n_64), .B (n_72), .Y (n_203));
  AND2X1 g7697__1377(.A (n_75), .B (n_74), .Y (n_202));
  AND2X1 g7754__3717(.A (n_58), .B (n_53), .Y (n_331));
  NOR2BX1 g7699__4599(.AN (n_75), .B (n_73), .Y (n_190));
  NAND2X1 g7700__3779(.A (n_71), .B (n_72), .Y (n_221));
  NAND2X1 g7701__2007(.A (n_70), .B (n_61), .Y (n_162));
  NAND2X1 g7702__1237(.A (n_71), .B (n_66), .Y (n_249));
  NAND2X1 g7705__1297(.A (n_70), .B (n_63), .Y (n_194));
  NOR2X1 g7706__2006(.A (n_69), .B (n_68), .Y (n_248));
  NOR2X1 g7707__2833(.A (n_73), .B (n_68), .Y (n_193));
  NOR2X1 g7720__7547(.A (rst_i), .B (n_46), .Y (n_67));
  NAND2X1 g7709__7765(.A (n_70), .B (n_66), .Y (n_258));
  NOR2BX1 g7710__9867(.AN (n_75), .B (n_65), .Y (n_216));
  NAND2X1 g7712__3377(.A (n_64), .B (n_66), .Y (n_227));
  NAND2X1 g7715__9719(.A (n_64), .B (n_63), .Y (n_301));
  NAND2X1 g7718__1591(.A (n_70), .B (n_72), .Y (n_212));
  NOR2BX1 g7749__6789(.AN (n_60), .B (n_62), .Y (n_277));
  NOR2X1 g7708__5927(.A (n_65), .B (n_68), .Y (n_251));
  NAND2X1 g7744__2001(.A (n_71), .B (n_63), .Y (n_252));
  NAND2X1 g7745__1122(.A (n_64), .B (n_61), .Y (n_191));
  NOR2BX1 g7750__9771(.AN (n_60), .B (n_59), .Y (n_151));
  AND2X1 g7752__3457(.A (n_58), .B (n_60), .Y (n_332));
  NOR2BX1 g7753__1279(.AN (n_60), .B (n_57), .Y (n_275));
  NOR2X1 g7755__6179(.A (rst_i), .B (n_56), .Y (n_169));
  NOR3X1 g7768__7837(.A (n_16), .B (n_41), .C (n_4), .Y (n_55));
  AOI21X1 g7767__7557(.A0 (n_54), .A1 (n_29), .B0 (n_328), .Y (n_103));
  INVX1 g7776(.A (n_53), .Y (n_79));
  NOR2X1 g7780__7654(.A (n_52), .B (n_57), .Y (n_306));
  NOR2X1 g7781__8867(.A (n_51), .B (n_62), .Y (n_101));
  NOR2X1 g7782__1377(.A (n_52), .B (n_59), .Y (n_310));
  NOR2X1 g7783__3717(.A (n_52), .B (n_62), .Y (n_153));
  NOR2X1 g7789__4599(.A (n_51), .B (n_57), .Y (n_311));
  NOR2X1 g7790__3779(.A (n_51), .B (n_59), .Y (n_325));
  NOR2X1 g7775__2007(.A (n_73), .B (n_49), .Y (n_161));
  SDFFHQX8 error_o_reg(.CK (clk_i), .D (n_32), .SI (wr_ptr[2]), .SE
       (scan_en), .Q (error_o));
  INVX1 g7761(.A (n_50), .Y (n_83));
  NOR2BX1 g7779__1237(.AN (n_58), .B (n_52), .Y (n_110));
  NOR2X1 g7758__1297(.A (n_69), .B (n_49), .Y (n_220));
  NAND2X1 g7704__2006(.A (n_48), .B (n_72), .Y (n_241));
  NOR2BX1 g7791__2833(.AN (n_58), .B (n_51), .Y (n_315));
  NAND2X1 g7713__7547(.A (n_48), .B (n_66), .Y (n_289));
  NAND2X1 g7714__7765(.A (n_48), .B (n_63), .Y (n_293));
  NAND2X1 g7746__9867(.A (n_48), .B (n_61), .Y (n_217));
  NOR2X1 g7759__3377(.A (n_65), .B (n_49), .Y (n_170));
  AND2X1 g7711__9719(.A (n_36), .B (n_74), .Y (n_257));
  AOI22X1 g7765__1591(.A0 (n_21), .A1 (n_45), .B0 (wr_ptr[3]), .B1
       (n_44), .Y (n_47));
  AOI22X1 g7766__6789(.A0 (n_9), .A1 (n_45), .B0 (wr_ptr[0]), .B1
       (n_44), .Y (n_46));
  NOR2X1 g7772__5927(.A (n_34), .B (n_35), .Y (n_50));
  OAI21X1 g7769__2001(.A0 (n_14), .A1 (n_363), .B0 (n_42), .Y (n_71));
  OAI21X1 g7773__1122(.A0 (wr_ptr[2]), .A1 (n_363), .B0 (n_42), .Y
       (n_70));
  OAI21X1 g7774__2005(.A0 (wr_ptr[2]), .A1 (n_28), .B0 (n_42), .Y
       (n_64));
  NOR2X1 g7777__9771(.A (rd_ptr[0]), .B (n_41), .Y (n_60));
  AOI22X1 g7762__3457(.A0 (n_15), .A1 (n_45), .B0 (wr_ptr[2]), .B1
       (n_44), .Y (n_39));
  AOI22X1 g7764__1279(.A0 (n_2), .A1 (n_45), .B0 (wr_ptr[1]), .B1
       (n_44), .Y (n_38));
  INVX1 g7785(.A (n_328), .Y (n_80));
  NOR2X1 g7778__6179(.A (n_37), .B (n_41), .Y (n_53));
  NOR3X1 g7787__7837(.A (n_18), .B (n_65), .C (n_44), .Y (n_56));
  INVX1 g7760(.A (n_36), .Y (n_68));
  NOR2X1 g7747__7557(.A (n_8), .B (n_35), .Y (n_75));
  NOR3X1 g7771__7654(.A (n_363), .B (rst_i), .C (n_34), .Y (n_36));
  NAND3X1 g7804__8867(.A (n_33), .B (n_37), .C (n_31), .Y (n_51));
  NAND3X1 g7788__1377(.A (n_19), .B (n_42), .C (n_45), .Y (n_49));
  OAI22X1 g7763__3717(.A0 (rst_i), .A1 (n_25), .B0 (n_31), .B1 (n_26),
       .Y (n_32));
  NAND3X1 g7803__4599(.A (rd_ptr[0]), .B (n_33), .C (n_31), .Y (n_52));
  OAI2BB1X1 g7770__3779(.A0N (wr_ptr[2]), .A1N (n_30), .B0 (n_42), .Y
       (n_48));
  AOI21X1 g7792__2007(.A0 (n_31), .A1 (rd_en_i), .B0 (rst_i), .Y
       (n_328));
  NAND2X1 g7786__1237(.A (n_30), .B (n_42), .Y (n_35));
  NAND2X1 g7798__1297(.A (rd_ptr[3]), .B (n_31), .Y (n_41));
  INVX1 g7800(.A (n_29), .Y (n_104));
  INVX1 g7793(.A (n_30), .Y (n_28));
  INVX1 g7794(.A (n_45), .Y (n_44));
  NOR2X1 g7805__2006(.A (empty_o), .B (n_26), .Y (n_29));
  NAND2X1 g7795__7547(.A (full_o), .B (wr_en_i), .Y (n_25));
  NOR2X1 g7796__7765(.A (wr_ptr[1]), .B (full_o), .Y (n_30));
  INVX1 g7806(.A (empty_o), .Y (n_31));
  NOR2BX1 g7799__9867(.AN (wr_en_i), .B (full_o), .Y (n_45));
  AND3X6 g7807__3377(.A (n_11), .B (n_12), .C (n_22), .Y (empty_o));
  AND2X6 g7810__9719(.A (n_13), .B (n_22), .Y (full_o));
  AOI221X1 g7812__1591(.A0 (rd_ptr[3]), .A1 (n_20), .B0 (wr_ptr[3]),
       .B1 (n_33), .C0 (n_10), .Y (n_22));
  OAI221X1 g7801__6789(.A0 (n_20), .A1 (n_19), .B0 (n_69), .B1 (n_18),
       .C0 (n_73), .Y (n_21));
  MX2XL g7802__5927(.A (n_16), .B (rd_ptr[2]), .S0 (rd_ptr[3]), .Y
       (n_17));
  OAI22X1 g7809__2001(.A0 (wr_ptr[2]), .A1 (n_18), .B0 (n_14), .B1
       (n_19), .Y (n_15));
  NOR2BX1 g7814__1122(.AN (n_12), .B (n_11), .Y (n_13));
  OAI221X1 g7819__2005(.A0 (wr_ptr[0]), .A1 (n_37), .B0 (rd_ptr[0]),
       .B1 (n_9), .C0 (n_7), .Y (n_10));
  OAI21X1 g7816__9771(.A0 (wr_ptr[3]), .A1 (n_34), .B0 (n_42), .Y
       (n_66));
  OAI21X1 g7818__3457(.A0 (n_20), .A1 (n_34), .B0 (n_42), .Y (n_63));
  OAI21X1 g7815__1279(.A0 (n_20), .A1 (n_8), .B0 (n_42), .Y (n_61));
  OAI21X1 g7817__6179(.A0 (wr_ptr[3]), .A1 (n_8), .B0 (n_42), .Y
       (n_72));
  AOI22X1 g7826__7837(.A0 (rd_ptr[1]), .A1 (n_1), .B0 (wr_ptr[1]), .B1
       (n_6), .Y (n_7));
  OAI22X1 g7825__7557(.A0 (rd_ptr[2]), .A1 (wr_ptr[2]), .B0 (n_14), .B1
       (n_5), .Y (n_12));
  OR4X1 g7821__7654(.A (n_5), .B (n_6), .C (rst_i), .D (n_4), .Y
       (n_62));
  NOR4X1 g7823__8867(.A (rd_ptr[1]), .B (rd_ptr[2]), .C (rst_i), .D
       (n_4), .Y (n_58));
  OR4X1 g7822__1377(.A (rd_ptr[1]), .B (n_5), .C (rst_i), .D (n_4), .Y
       (n_57));
  OAI22X1 g7828__3717(.A0 (wr_ptr[1]), .A1 (n_9), .B0 (wr_ptr[0]), .B1
       (n_1), .Y (n_2));
  AOI22X1 g7827__4599(.A0 (rd_ptr[0]), .A1 (n_6), .B0 (rd_ptr[1]), .B1
       (n_37), .Y (n_0));
  OR2XL g7811__3779(.A (n_5), .B (n_54), .Y (n_16));
  OR4X1 g7820__2007(.A (rd_ptr[2]), .B (n_6), .C (rst_i), .D (n_4), .Y
       (n_59));
  XNOR2X1 g7824__1237(.A (rd_toggle_flag), .B (wr_toggle_flag), .Y
       (n_11));
  NAND2X1 g7831__1297(.A (n_9), .B (wr_en_i), .Y (n_34));
  NAND2X1 g7836__2006(.A (wr_ptr[3]), .B (n_14), .Y (n_73));
  NAND2X1 g7834__2833(.A (rd_en_i), .B (n_42), .Y (n_26));
  INVX1 g7813(.A (n_18), .Y (n_19));
  NAND2X1 g7837__7547(.A (n_20), .B (wr_ptr[2]), .Y (n_69));
  NAND2X1 g7835__7765(.A (rd_ptr[1]), .B (rd_ptr[0]), .Y (n_54));
  NAND2X1 g7832__9867(.A (wr_ptr[3]), .B (wr_ptr[2]), .Y (n_65));
  NAND2X1 g7829__3377(.A (wr_ptr[0]), .B (wr_en_i), .Y (n_8));
  NOR2X1 g7830__9719(.A (wr_ptr[3]), .B (wr_ptr[2]), .Y (n_74));
  NAND2X1 g7838__1591(.A (wr_ptr[0]), .B (wr_ptr[1]), .Y (n_18));
  INVX1 g7841(.A (wr_ptr[1]), .Y (n_1));
  INVX1 g7848(.A (wr_ptr[2]), .Y (n_14));
  INVX1 g7847(.A (rd_ptr[2]), .Y (n_5));
  INVX1 g7844(.A (wr_ptr[3]), .Y (n_20));
  INVX1 g7845(.A (rst_i), .Y (n_42));
  INVX1 g7840(.A (rd_ptr[3]), .Y (n_33));
  INVX1 g7846(.A (wr_ptr[0]), .Y (n_9));
  INVX1 g7843(.A (rd_ptr[0]), .Y (n_37));
  INVX1 g7839(.A (rd_en_i), .Y (n_4));
  INVX1 g7842(.A (rd_ptr[1]), .Y (n_6));
  NOR2BX1 g2(.AN (n_74), .B (n_49), .Y (n_362));
  NAND2BX1 g7996(.AN (full_o), .B (wr_ptr[1]), .Y (n_363));
  NOR2BX1 g7997(.AN (n_75), .B (n_69), .Y (n_364));
  TLATNXL ts_lockup_latchn_clkc1_intno48_i(.GN (clk_i), .D
       (\fifo[10] [6]), .Q (ts_so[0]), .QN (UNCONNECTED8));
  TLATNXL ts_lockup_latchn_clkc2_intno97_i(.GN (clk_i), .D (\fifo[7]
       [6]), .Q (ts_so[1]), .QN (UNCONNECTED9));
  TLATNXL ts_lockup_latchn_clkc3_intno146_i(.GN (clk_i), .D (error_o),
       .Q (ts_so[2]), .QN (UNCONNECTED10));
  DLY4X4 tessent_persistent_cell_buf_extsi147_i(.A (ts_si[0]), .Y
       (ts_pbuf_extsi147_));
  DLY4X4 tessent_persistent_cell_buf_extsi148_i(.A (ts_si[1]), .Y
       (ts_pbuf_extsi148_));
  DLY4X4 tessent_persistent_cell_buf_extsi149_i(.A (ts_si[2]), .Y
       (ts_pbuf_extsi149_));
endmodule

module sync_fifo_edt_top(clk_i, rst_i, wr_en_i, rd_en_i, wr_data_i,
     rd_data_o, full_o, empty_o, error_o, scan_en, edt_clock,
     edt_update, edt_bypass, edt_channels_in1, edt_channels_in2,
     edt_channels_in3, edt_channels_out1, edt_channels_out2,
     edt_channels_out3);
  input clk_i, rst_i, wr_en_i, rd_en_i, scan_en, edt_clock, edt_update,
       edt_bypass, edt_channels_in1, edt_channels_in2, edt_channels_in3;
  input [7:0] wr_data_i;
  output [7:0] rd_data_o;
  output full_o, empty_o, error_o, edt_channels_out1,
       edt_channels_out2, edt_channels_out3;
  wire clk_i, rst_i, wr_en_i, rd_en_i, scan_en, edt_clock, edt_update,
       edt_bypass, edt_channels_in1, edt_channels_in2, edt_channels_in3;
  wire [7:0] wr_data_i;
  wire [7:0] rd_data_o;
  wire full_o, empty_o, error_o, edt_channels_out1, edt_channels_out2,
       edt_channels_out3;
  wire [2:0] edt_scan_out;
  wire [2:0] edt_scan_in;
  sync_fifo_edt sync_fifo_edt_i(.edt_clock (edt_clock), .edt_update
       (edt_update), .edt_bypass (edt_bypass), .edt_channels_in
       ({edt_channels_in3, edt_channels_in2, edt_channels_in1}),
       .edt_channels_out ({edt_channels_out3, edt_channels_out2,
       edt_channels_out1}), .edt_scan_in (edt_scan_in), .edt_scan_out
       (edt_scan_out));
  sync_fifo sync_fifo_i(.clk_i (clk_i), .rst_i (rst_i), .wr_en_i
       (wr_en_i), .rd_en_i (rd_en_i), .wr_data_i (wr_data_i),
       .rd_data_o (rd_data_o), .full_o (full_o), .empty_o (empty_o),
       .error_o (error_o), .ts_si (edt_scan_in), .ts_so (edt_scan_out),
       .scan_en (scan_en));
endmodule

