/* Generated by Tessent Shell 2022.4 at Fri Sep 18 11:49:46 IST 2026 */

`timescale 1ns / 1ns

module sync_fifo(clk_i, rst_i, wr_en_i, rd_en_i, wr_data_i, rd_data_o, full_o, 
                 empty_o, error_o, ts_si, ts_so, scan_en);
  input  [7:0] wr_data_i;
  input  [2:0] ts_si;
  input  clk_i, rst_i, wr_en_i, rd_en_i, scan_en;
  output [7:0] rd_data_o;
  output [2:0] ts_so;
  output full_o, empty_o, error_o;

  wire [7:0] \fifo[8] , \fifo[9] , \fifo[4] , \fifo[12] , \fifo[2] , 
             \fifo[15] , \fifo[0] , \fifo[11] , \fifo[13] , \fifo[5] , 
             \fifo[7] , \fifo[10] , \fifo[1] , \fifo[3] , \fifo[14] , 
             \fifo[6] ;
  wire [3:0] rd_ptr, wr_ptr;
  wire n_0, n_1, n_2, n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11, n_12, n_13, 
       n_14, n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_25, n_26, n_28, 
       n_29, n_30, n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_41, 
       n_42, n_44, n_45, n_46, n_47, n_48, n_49, n_50, n_51, n_52, n_53, n_54, 
       n_55, n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64, n_65, n_66, 
       n_67, n_68, n_69, n_70, n_71, n_72, n_73, n_74, n_75, n_76, n_77, n_78, 
       n_79, n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87, n_88, n_89, n_90, 
       n_91, n_92, n_93, n_94, n_95, n_96, n_97, n_98, n_99, n_100, n_101, 
       n_102, n_103, n_104, n_105, n_106, n_107, n_108, n_109, n_110, n_111, 
       n_112, n_113, n_114, n_115, n_116, n_117, n_118, n_119, n_120, n_121, 
       n_122, n_123, n_124, n_125, n_126, n_127, n_128, n_129, n_130, n_131, 
       n_132, n_133, n_134, n_135, n_136, n_137, n_138, n_139, n_140, n_141, 
       n_142, n_143, n_144, n_145, n_146, n_147, n_148, n_149, n_150, n_151, 
       n_152, n_153, n_154, n_155, n_156, n_157, n_158, n_159, n_160, n_161, 
       n_162, n_163, n_164, n_165, n_166, n_167, n_168, n_169, n_170, n_171, 
       n_172, n_173, n_174, n_175, n_176, n_177, n_178, n_179, n_180, n_181, 
       n_182, n_183, n_184, n_185, n_186, n_187, n_188, n_189, n_190, n_191, 
       n_192, n_193, n_194, n_195, n_196, n_197, n_198, n_199, n_200, n_201, 
       n_202, n_203, n_204, n_205, n_206, n_207, n_208, n_209, n_210, n_212, 
       n_213, n_214, n_215, n_216, n_217, n_218, n_219, n_220, n_221, n_222, 
       n_223, n_224, n_225, n_226, n_227, n_228, n_229, n_230, n_231, n_232, 
       n_233, n_234, n_235, n_236, n_237, n_238, n_239, n_241, n_242, n_243, 
       n_244, n_245, n_246, n_247, n_248, n_249, n_250, n_251, n_252, n_253, 
       n_254, n_255, n_256, n_257, n_258, n_259, n_260, n_261, n_262, n_263, 
       n_264, n_265, n_266, n_267, n_268, n_269, n_270, n_271, n_272, n_273, 
       n_274, n_275, n_276, n_277, n_278, n_279, n_280, n_281, n_282, n_283, 
       n_284, n_285, n_286, n_287, n_288, n_289, n_290, n_291, n_292, n_293, 
       n_294, n_295, n_296, n_297, n_298, n_299, n_300, n_301, n_302, n_303, 
       n_304, n_305, n_306, n_307, n_308, n_309, n_310, n_311, n_312, n_313, 
       n_314, n_315, n_316, n_317, n_318, n_319, n_320, n_321, n_322, n_323, 
       n_324, n_325, n_326, n_327, n_328, n_329, n_330, n_331, n_332, n_333, 
       n_334, n_335, n_336, n_337, n_338, n_339, n_340, n_341, n_342, n_343, 
       n_344, n_345, n_346, n_347, n_348, n_362, n_363, n_364, rd_toggle_flag, 
       wr_toggle_flag, ts_lockup_latchn_clkc1_intno48_, 
       ts_lockup_latchn_clkc2_intno97_, ts_lockup_latchn_clkc3_intno146_, 
       ts_pbuf_extsi147_, ts_pbuf_extsi148_, ts_pbuf_extsi149_;

  assign ts_so[0] = ts_lockup_latchn_clkc1_intno48_;
  assign ts_so[1] = ts_lockup_latchn_clkc2_intno97_;
  assign ts_so[2] = ts_lockup_latchn_clkc3_intno146_;
  SDFFHQX8 \rd_data_o_reg[0] (
      .Q(rd_data_o[0]), .D(n_347), .SE(scan_en), .SI(ts_pbuf_extsi147_), .CK(clk_i)
  );
  SDFFHQX8 \rd_data_o_reg[6] (
      .Q(rd_data_o[6]), .D(n_343), .SE(scan_en), .SI(rd_data_o[0]), .CK(clk_i)
  );
  SDFFHQX8 \rd_data_o_reg[1] (
      .Q(rd_data_o[1]), .D(n_346), .SE(scan_en), .SI(rd_data_o[6]), .CK(clk_i)
  );
  SDFFHQX8 \rd_data_o_reg[3] (
      .Q(rd_data_o[3]), .D(n_344), .SE(scan_en), .SI(rd_data_o[1]), .CK(clk_i)
  );
  SDFFHQX8 \rd_data_o_reg[4] (
      .Q(rd_data_o[4]), .D(n_345), .SE(scan_en), .SI(rd_data_o[3]), .CK(clk_i)
  );
  SDFFHQX8 \rd_data_o_reg[5] (
      .Q(rd_data_o[5]), .D(n_348), .SE(scan_en), .SI(rd_data_o[4]), .CK(clk_i)
  );
  SDFFHQX8 \rd_data_o_reg[7] (
      .Q(rd_data_o[7]), .D(n_342), .SE(scan_en), .SI(rd_data_o[5]), .CK(clk_i)
  );
  SDFFHQX8 \rd_data_o_reg[2] (
      .Q(rd_data_o[2]), .D(n_341), .SE(scan_en), .SI(rd_data_o[7]), .CK(clk_i)
  );
  NAND4BX1 g7363__7837(
      .Y(n_348), .AN(n_340), .B(n_100), .C(n_329), .D(n_309)
  );
  NAND4BX1 g7359__7557(
      .Y(n_347), .AN(n_338), .B(n_93), .C(n_322), .D(n_316)
  );
  NAND4BX1 g7360__7654(
      .Y(n_346), .AN(n_337), .B(n_98), .C(n_323), .D(n_314)
  );
  NAND4BX1 g7364__8867(
      .Y(n_345), .AN(n_335), .B(n_109), .C(n_330), .D(n_312)
  );
  NAND4BX1 g7365__1377(
      .Y(n_344), .AN(n_336), .B(n_85), .C(n_326), .D(n_313)
  );
  NAND4BX1 g7366__3717(
      .Y(n_343), .AN(n_339), .B(n_102), .C(n_307), .D(n_308)
  );
  NAND4BX1 g7367__4599(
      .Y(n_342), .AN(n_317), .B(n_154), .C(n_321), .D(n_334)
  );
  NAND4BX1 g7368__3779(
      .Y(n_341), .AN(n_318), .B(n_137), .C(n_324), .D(n_333)
  );
  NAND4XL g7432__2007(
      .Y(n_340), .A(n_266), .B(n_127), .C(n_129), .D(n_267)
  );
  NAND4XL g7433__1237(
      .Y(n_339), .A(n_281), .B(n_155), .C(n_156), .D(n_291)
  );
  NAND4XL g7434__1297(
      .Y(n_338), .A(n_276), .B(n_143), .C(n_144), .D(n_278)
  );
  NAND4XL g7435__2006(
      .Y(n_337), .A(n_140), .B(n_139), .C(n_273), .D(n_274)
  );
  NAND4XL g7436__2833(
      .Y(n_336), .A(n_269), .B(n_134), .C(n_146), .D(n_270)
  );
  NAND4XL g7437__7547(
      .Y(n_335), .A(n_272), .B(n_130), .C(n_132), .D(n_268)
  );
  AOI221X1 g7508__7765(
      .Y(n_334), .A0(\fifo[8] [7]), .A1(n_332), .B0(\fifo[9] [7]), .B1(n_331), 
      .C0(n_152)
  );
  AOI221X1 g7509__9867(
      .Y(n_333), .A0(\fifo[8] [2]), .A1(n_332), .B0(\fifo[9] [2]), .B1(n_331), 
      .C0(n_136)
  );
  SDFFQXL \fifo_reg[4][6] (
      .Q(\fifo[4] [6]), .D(n_280), .SE(scan_en), .SI(rd_data_o[2]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[4][2] (
      .Q(\fifo[4] [2]), .D(n_285), .SE(scan_en), .SI(\fifo[4] [6]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[4][3] (
      .Q(\fifo[4] [3]), .D(n_283), .SE(scan_en), .SI(\fifo[4] [2]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[4][4] (
      .Q(\fifo[4] [4]), .D(n_290), .SE(scan_en), .SI(\fifo[4] [3]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[4][5] (
      .Q(\fifo[4] [5]), .D(n_282), .SE(scan_en), .SI(\fifo[4] [4]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[4][1] (
      .Q(\fifo[4] [1]), .D(n_295), .SE(scan_en), .SI(\fifo[4] [5]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[4][7] (
      .Q(\fifo[4] [7]), .D(n_279), .SE(scan_en), .SI(\fifo[4] [1]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[12][0] (
      .Q(\fifo[12] [0]), .D(n_271), .SE(scan_en), .SI(\fifo[4] [7]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[12][1] (
      .Q(\fifo[12] [1]), .D(n_265), .SE(scan_en), .SI(\fifo[12] [0]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[12][2] (
      .Q(\fifo[12] [2]), .D(n_264), .SE(scan_en), .SI(\fifo[12] [1]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[4][0] (
      .Q(\fifo[4] [0]), .D(n_284), .SE(scan_en), .SI(\fifo[12] [2]), .CK(clk_i)
  );
  SDFFQXL rd_toggle_flag_reg(
      .Q(rd_toggle_flag), .D(n_303), .SE(scan_en), .SI(\fifo[4] [0]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[12][4] (
      .Q(\fifo[12] [4]), .D(n_262), .SE(scan_en), .SI(rd_toggle_flag), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[12][5] (
      .Q(\fifo[12] [5]), .D(n_261), .SE(scan_en), .SI(\fifo[12] [4]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[12][6] (
      .Q(\fifo[12] [6]), .D(n_304), .SE(scan_en), .SI(\fifo[12] [5]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[12][7] (
      .Q(\fifo[12] [7]), .D(n_294), .SE(scan_en), .SI(\fifo[12] [6]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[8][1] (
      .Q(\fifo[8] [1]), .D(n_298), .SE(scan_en), .SI(\fifo[12] [7]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[8][2] (
      .Q(\fifo[8] [2]), .D(n_302), .SE(scan_en), .SI(\fifo[8] [1]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[8][3] (
      .Q(\fifo[8] [3]), .D(n_297), .SE(scan_en), .SI(\fifo[8] [2]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[8][4] (
      .Q(\fifo[8] [4]), .D(n_296), .SE(scan_en), .SI(\fifo[8] [3]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[8][5] (
      .Q(\fifo[8] [5]), .D(n_305), .SE(scan_en), .SI(\fifo[8] [4]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[8][6] (
      .Q(\fifo[8] [6]), .D(n_287), .SE(scan_en), .SI(\fifo[8] [5]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[8][7] (
      .Q(\fifo[8] [7]), .D(n_286), .SE(scan_en), .SI(\fifo[8] [6]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[8][0] (
      .Q(\fifo[8] [0]), .D(n_299), .SE(scan_en), .SI(\fifo[8] [7]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[12][3] (
      .Q(\fifo[12] [3]), .D(n_263), .SE(scan_en), .SI(\fifo[8] [0]), .CK(clk_i)
  );
  AOI222X1 g7515__3377(
      .Y(n_330), .A0(rd_data_o[4]), .A1(n_328), .B0(\fifo[2] [4]), .B1(n_325), 
      .C0(\fifo[15] [4]), .C1(n_327)
  );
  AOI222X1 g7516__9719(
      .Y(n_329), .A0(rd_data_o[5]), .A1(n_328), .B0(\fifo[0] [5]), .B1(n_315), 
      .C0(\fifo[15] [5]), .C1(n_327)
  );
  AOI222X1 g7514__1591(
      .Y(n_326), .A0(rd_data_o[3]), .A1(n_328), .B0(\fifo[2] [3]), .B1(n_325), 
      .C0(\fifo[15] [3]), .C1(n_327)
  );
  AOI222X1 g7513__6789(
      .Y(n_324), .A0(\fifo[11] [2]), .A1(n_320), .B0(\fifo[13] [2]), .B1(n_319), 
      .C0(\fifo[15] [2]), .C1(n_327)
  );
  AOI222X1 g7512__5927(
      .Y(n_323), .A0(rd_data_o[1]), .A1(n_328), .B0(\fifo[2] [1]), .B1(n_325), 
      .C0(\fifo[15] [1]), .C1(n_327)
  );
  AOI222X1 g7511__2001(
      .Y(n_322), .A0(rd_data_o[0]), .A1(n_328), .B0(\fifo[5] [0]), .B1(n_306), 
      .C0(\fifo[15] [0]), .C1(n_327)
  );
  AOI222X1 g7510__1122(
      .Y(n_321), .A0(\fifo[11] [7]), .A1(n_320), .B0(\fifo[13] [7]), .B1(n_319), 
      .C0(\fifo[15] [7]), .C1(n_327)
  );
  SDFFQXL \fifo_reg[11][4] (
      .Q(\fifo[11] [4]), .D(n_148), .SE(scan_en), .SI(\fifo[12] [3]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[7][0] (
      .Q(\fifo[7] [0]), .D(n_223), .SE(scan_en), .SI(\fifo[11] [4]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[10][3] (
      .Q(\fifo[10] [3]), .D(n_188), .SE(scan_en), .SI(\fifo[7] [0]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[5][7] (
      .Q(\fifo[5] [7]), .D(n_174), .SE(scan_en), .SI(\fifo[10] [3]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[1][6] (
      .Q(\fifo[1] [6]), .D(n_147), .SE(scan_en), .SI(\fifo[5] [7]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[3][4] (
      .Q(\fifo[3] [4]), .D(n_198), .SE(scan_en), .SI(\fifo[1] [6]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[14][2] (
      .Q(\fifo[14] [2]), .D(n_254), .SE(scan_en), .SI(\fifo[3] [4]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[10][0] (
      .Q(\fifo[10] [0]), .D(n_176), .SE(scan_en), .SI(\fifo[14] [2]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[1][3] (
      .Q(\fifo[1] [3]), .D(n_181), .SE(scan_en), .SI(\fifo[10] [0]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[10][1] (
      .Q(\fifo[10] [1]), .D(n_199), .SE(scan_en), .SI(\fifo[1] [3]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[10][2] (
      .Q(\fifo[10] [2]), .D(n_195), .SE(scan_en), .SI(\fifo[10] [1]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[1][2] (
      .Q(\fifo[1] [2]), .D(n_179), .SE(scan_en), .SI(\fifo[10] [2]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[10][4] (
      .Q(\fifo[10] [4]), .D(n_183), .SE(scan_en), .SI(\fifo[1] [2]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[10][5] (
      .Q(\fifo[10] [5]), .D(n_178), .SE(scan_en), .SI(\fifo[10] [4]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[1][4] (
      .Q(\fifo[1] [4]), .D(n_160), .SE(scan_en), .SI(\fifo[10] [5]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[10][6] (
      .Q(\fifo[10] [6]), .D(n_175), .SE(scan_en), .SI(\fifo[1] [4]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[0][4] (
      .Q(\fifo[0] [4]), .D(n_245), .SE(scan_en), .SI(ts_pbuf_extsi148_), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[13][6] (
      .Q(\fifo[13] [6]), .D(n_121), .SE(scan_en), .SI(\fifo[0] [4]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[3][3] (
      .Q(\fifo[3] [3]), .D(n_200), .SE(scan_en), .SI(\fifo[13] [6]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[11][0] (
      .Q(\fifo[11] [0]), .D(n_165), .SE(scan_en), .SI(\fifo[3] [3]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[11][1] (
      .Q(\fifo[11] [1]), .D(n_163), .SE(scan_en), .SI(\fifo[11] [0]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[11][2] (
      .Q(\fifo[11] [2]), .D(n_157), .SE(scan_en), .SI(\fifo[11] [1]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[2][7] (
      .Q(\fifo[2] [7]), .D(n_260), .SE(scan_en), .SI(\fifo[11] [2]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[1][5] (
      .Q(\fifo[1] [5]), .D(n_159), .SE(scan_en), .SI(\fifo[2] [7]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[11][3] (
      .Q(\fifo[11] [3]), .D(n_149), .SE(scan_en), .SI(\fifo[1] [5]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[14][6] (
      .Q(\fifo[14] [6]), .D(n_239), .SE(scan_en), .SI(\fifo[11] [3]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[10][7] (
      .Q(\fifo[10] [7]), .D(n_172), .SE(scan_en), .SI(\fifo[14] [6]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[11][5] (
      .Q(\fifo[11] [5]), .D(n_145), .SE(scan_en), .SI(\fifo[10] [7]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[11][7] (
      .Q(\fifo[11] [7]), .D(n_138), .SE(scan_en), .SI(\fifo[11] [5]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[5][0] (
      .Q(\fifo[5] [0]), .D(n_141), .SE(scan_en), .SI(\fifo[11] [7]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[14][1] (
      .Q(\fifo[14] [1]), .D(n_113), .SE(scan_en), .SI(\fifo[5] [0]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[5][1] (
      .Q(\fifo[5] [1]), .D(n_128), .SE(scan_en), .SI(\fifo[14] [1]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[5][2] (
      .Q(\fifo[5] [2]), .D(n_126), .SE(scan_en), .SI(\fifo[5] [1]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[1][7] (
      .Q(\fifo[1] [7]), .D(n_131), .SE(scan_en), .SI(\fifo[5] [2]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[5][3] (
      .Q(\fifo[5] [3]), .D(n_125), .SE(scan_en), .SI(\fifo[1] [7]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[0][1] (
      .Q(\fifo[0] [1]), .D(n_133), .SE(scan_en), .SI(\fifo[5] [3]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[2][0] (
      .Q(\fifo[2] [0]), .D(n_233), .SE(scan_en), .SI(\fifo[0] [1]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[5][4] (
      .Q(\fifo[5] [4]), .D(n_242), .SE(scan_en), .SI(\fifo[2] [0]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[5][5] (
      .Q(\fifo[5] [5]), .D(n_255), .SE(scan_en), .SI(\fifo[5] [4]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[13][0] (
      .Q(\fifo[13] [0]), .D(n_246), .SE(scan_en), .SI(\fifo[5] [5]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[11][6] (
      .Q(\fifo[11] [6]), .D(n_142), .SE(scan_en), .SI(\fifo[13] [0]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[13][2] (
      .Q(\fifo[13] [2]), .D(n_116), .SE(scan_en), .SI(\fifo[11] [6]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[5][6] (
      .Q(\fifo[5] [6]), .D(n_120), .SE(scan_en), .SI(\fifo[13] [2]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[13][3] (
      .Q(\fifo[13] [3]), .D(n_124), .SE(scan_en), .SI(\fifo[5] [6]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[13][4] (
      .Q(\fifo[13] [4]), .D(n_123), .SE(scan_en), .SI(\fifo[13] [3]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[13][5] (
      .Q(\fifo[13] [5]), .D(n_122), .SE(scan_en), .SI(\fifo[13] [4]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[2][1] (
      .Q(\fifo[2] [1]), .D(n_117), .SE(scan_en), .SI(\fifo[13] [5]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[13][7] (
      .Q(\fifo[13] [7]), .D(n_118), .SE(scan_en), .SI(\fifo[2] [1]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[14][0] (
      .Q(\fifo[14] [0]), .D(n_115), .SE(scan_en), .SI(\fifo[13] [7]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[6][0] (
      .Q(\fifo[6] [0]), .D(n_119), .SE(scan_en), .SI(\fifo[14] [0]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[6][1] (
      .Q(\fifo[6] [1]), .D(n_256), .SE(scan_en), .SI(\fifo[6] [0]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[0][0] (
      .Q(\fifo[0] [0]), .D(n_197), .SE(scan_en), .SI(\fifo[6] [1]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[9][3] (
      .Q(\fifo[9] [3]), .D(n_185), .SE(scan_en), .SI(\fifo[0] [0]), .CK(clk_i)
  );
  NAND4XL g7568__2005(
      .Y(n_318), .A(n_95), .B(n_97), .C(n_90), .D(n_91)
  );
  NAND4XL g7638__9771(
      .Y(n_317), .A(n_86), .B(n_108), .C(n_96), .D(n_111)
  );
  AOI221X1 g7647__3457(
      .Y(n_316), .A0(\fifo[1] [0]), .A1(n_110), .B0(\fifo[0] [0]), .B1(n_315), 
      .C0(n_92)
  );
  AOI221X1 g7648__1279(
      .Y(n_314), .A0(\fifo[6] [1]), .A1(n_101), .B0(\fifo[0] [1]), .B1(n_315), 
      .C0(n_87)
  );
  AOI221X1 g7649__6179(
      .Y(n_313), .A0(\fifo[4] [3]), .A1(n_311), .B0(\fifo[3] [3]), .B1(n_310), 
      .C0(n_99)
  );
  AOI221X1 g7650__7837(
      .Y(n_312), .A0(\fifo[4] [4]), .A1(n_311), .B0(\fifo[3] [4]), .B1(n_310), 
      .C0(n_88)
  );
  AOI221X1 g7651__7557(
      .Y(n_309), .A0(\fifo[4] [5]), .A1(n_311), .B0(\fifo[3] [5]), .B1(n_310), 
      .C0(n_94)
  );
  AOI221X1 g7652__7654(
      .Y(n_308), .A0(\fifo[4] [6]), .A1(n_311), .B0(\fifo[0] [6]), .B1(n_315), 
      .C0(n_89)
  );
  AOI222X1 g7517__8867(
      .Y(n_307), .A0(rd_data_o[6]), .A1(n_328), .B0(\fifo[5] [6]), .B1(n_306), 
      .C0(\fifo[15] [6]), .C1(n_327)
  );
  SDFFQXL \fifo_reg[0][6] (
      .Q(\fifo[0] [6]), .D(n_206), .SE(scan_en), .SI(\fifo[9] [3]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[2][5] (
      .Q(\fifo[2] [5]), .D(n_225), .SE(scan_en), .SI(\fifo[0] [6]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[7][1] (
      .Q(\fifo[7] [1]), .D(n_222), .SE(scan_en), .SI(\fifo[2] [5]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[2][6] (
      .Q(\fifo[2] [6]), .D(n_214), .SE(scan_en), .SI(\fifo[7] [1]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[7][2] (
      .Q(\fifo[7] [2]), .D(n_219), .SE(scan_en), .SI(\fifo[2] [6]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[13][1] (
      .Q(\fifo[13] [1]), .D(n_218), .SE(scan_en), .SI(\fifo[7] [2]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[7][3] (
      .Q(\fifo[7] [3]), .D(n_215), .SE(scan_en), .SI(\fifo[13] [1]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[7][4] (
      .Q(\fifo[7] [4]), .D(n_210), .SE(scan_en), .SI(\fifo[7] [3]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[7][5] (
      .Q(\fifo[7] [5]), .D(n_209), .SE(scan_en), .SI(\fifo[7] [4]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[0][5] (
      .Q(\fifo[0] [5]), .D(n_228), .SE(scan_en), .SI(\fifo[7] [5]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[3][0] (
      .Q(\fifo[3] [0]), .D(n_213), .SE(scan_en), .SI(\fifo[0] [5]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[7][6] (
      .Q(\fifo[7] [6]), .D(n_208), .SE(scan_en), .SI(\fifo[3] [0]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[0][7] (
      .Q(\fifo[0] [7]), .D(n_224), .SE(scan_en), .SI(ts_pbuf_extsi149_), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[14][3] (
      .Q(\fifo[14] [3]), .D(n_253), .SE(scan_en), .SI(\fifo[0] [7]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[3][1] (
      .Q(\fifo[3] [1]), .D(n_236), .SE(scan_en), .SI(\fifo[14] [3]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[3][2] (
      .Q(\fifo[3] [2]), .D(n_205), .SE(scan_en), .SI(\fifo[3] [1]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[9][1] (
      .Q(\fifo[9] [1]), .D(n_189), .SE(scan_en), .SI(\fifo[3] [2]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[1][0] (
      .Q(\fifo[1] [0]), .D(n_238), .SE(scan_en), .SI(\fifo[9] [1]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[3][5] (
      .Q(\fifo[3] [5]), .D(n_196), .SE(scan_en), .SI(\fifo[1] [0]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[9][0] (
      .Q(\fifo[9] [0]), .D(n_192), .SE(scan_en), .SI(\fifo[3] [5]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[3][6] (
      .Q(\fifo[3] [6]), .D(n_187), .SE(scan_en), .SI(\fifo[9] [0]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[6][3] (
      .Q(\fifo[6] [3]), .D(n_243), .SE(scan_en), .SI(\fifo[3] [6]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[9][2] (
      .Q(\fifo[9] [2]), .D(n_186), .SE(scan_en), .SI(\fifo[6] [3]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[9][4] (
      .Q(\fifo[9] [4]), .D(n_182), .SE(scan_en), .SI(\fifo[9] [2]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[3][7] (
      .Q(\fifo[3] [7]), .D(n_184), .SE(scan_en), .SI(\fifo[9] [4]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[9][5] (
      .Q(\fifo[9] [5]), .D(n_180), .SE(scan_en), .SI(\fifo[3] [7]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[0][2] (
      .Q(\fifo[0] [2]), .D(n_114), .SE(scan_en), .SI(\fifo[9] [5]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[2][2] (
      .Q(\fifo[2] [2]), .D(n_259), .SE(scan_en), .SI(\fifo[0] [2]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[9][7] (
      .Q(\fifo[9] [7]), .D(n_177), .SE(scan_en), .SI(\fifo[2] [2]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[14][4] (
      .Q(\fifo[14] [4]), .D(n_247), .SE(scan_en), .SI(\fifo[9] [7]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[6][2] (
      .Q(\fifo[6] [2]), .D(n_250), .SE(scan_en), .SI(\fifo[14] [4]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[15][5] (
      .Q(\fifo[15] [5]), .D(n_173), .SE(scan_en), .SI(\fifo[6] [2]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[15][1] (
      .Q(\fifo[15] [1]), .D(n_166), .SE(scan_en), .SI(\fifo[15] [5]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[15][0] (
      .Q(\fifo[15] [0]), .D(n_158), .SE(scan_en), .SI(\fifo[15] [1]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[15][6] (
      .Q(\fifo[15] [6]), .D(n_135), .SE(scan_en), .SI(\fifo[15] [0]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[15][2] (
      .Q(\fifo[15] [2]), .D(n_167), .SE(scan_en), .SI(\fifo[15] [6]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[15][4] (
      .Q(\fifo[15] [4]), .D(n_171), .SE(scan_en), .SI(\fifo[15] [2]), .CK(clk_i)
  );
  SDFFQXL wr_toggle_flag_reg(
      .Q(wr_toggle_flag), .D(n_164), .SE(scan_en), .SI(\fifo[15] [4]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[15][7] (
      .Q(\fifo[15] [7]), .D(n_150), .SE(scan_en), .SI(wr_toggle_flag), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[2][3] (
      .Q(\fifo[2] [3]), .D(n_237), .SE(scan_en), .SI(\fifo[15] [7]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[14][7] (
      .Q(\fifo[14] [7]), .D(n_235), .SE(scan_en), .SI(\fifo[2] [3]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[6][4] (
      .Q(\fifo[6] [4]), .D(n_234), .SE(scan_en), .SI(\fifo[14] [7]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[0][3] (
      .Q(\fifo[0] [3]), .D(n_112), .SE(scan_en), .SI(\fifo[6] [4]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[2][4] (
      .Q(\fifo[2] [4]), .D(n_232), .SE(scan_en), .SI(\fifo[0] [3]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[6][5] (
      .Q(\fifo[6] [5]), .D(n_231), .SE(scan_en), .SI(\fifo[2] [4]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[6][6] (
      .Q(\fifo[6] [6]), .D(n_230), .SE(scan_en), .SI(\fifo[6] [5]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[1][1] (
      .Q(\fifo[1] [1]), .D(n_204), .SE(scan_en), .SI(\fifo[6] [6]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[15][3] (
      .Q(\fifo[15] [3]), .D(n_168), .SE(scan_en), .SI(\fifo[1] [1]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[14][5] (
      .Q(\fifo[14] [5]), .D(n_244), .SE(scan_en), .SI(\fifo[15] [3]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[6][7] (
      .Q(\fifo[6] [7]), .D(n_229), .SE(scan_en), .SI(\fifo[14] [5]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[9][6] (
      .Q(\fifo[9] [6]), .D(n_201), .SE(scan_en), .SI(\fifo[6] [7]), .CK(clk_i)
  );
  SDFFQXL \fifo_reg[7][7] (
      .Q(\fifo[7] [7]), .D(n_207), .SE(scan_en), .SI(\fifo[9] [6]), .CK(clk_i)
  );
  AO22XL g7618__1377(
      .Y(n_305), .A0(\fifo[8] [5]), .A1(n_301), .B0(wr_data_i[5]), .B1(n_300)
  );
  AO22XL g7505__3717(
      .Y(n_304), .A0(\fifo[12] [6]), .A1(n_293), .B0(wr_data_i[6]), .B1(n_292)
  );
  NOR2X1 g7507__4599(
      .Y(n_303), .A(rst_i), .B(n_107)
  );
  AO22XL g7614__3779(
      .Y(n_302), .A0(\fifo[8] [2]), .A1(n_301), .B0(wr_data_i[2]), .B1(n_300)
  );
  AO22XL g7608__2007(
      .Y(n_299), .A0(\fifo[8] [0]), .A1(n_301), .B0(wr_data_i[0]), .B1(n_300)
  );
  AO22XL g7611__1237(
      .Y(n_298), .A0(\fifo[8] [1]), .A1(n_301), .B0(wr_data_i[1]), .B1(n_300)
  );
  AO22XL g7615__1297(
      .Y(n_297), .A0(\fifo[8] [3]), .A1(n_301), .B0(wr_data_i[3]), .B1(n_300)
  );
  AO22XL g7617__2006(
      .Y(n_296), .A0(\fifo[8] [4]), .A1(n_301), .B0(wr_data_i[4]), .B1(n_300)
  );
  AO22XL g7518__2833(
      .Y(n_295), .A0(\fifo[4] [1]), .A1(n_289), .B0(wr_data_i[1]), .B1(n_288)
  );
  AO22XL g7503__7547(
      .Y(n_294), .A0(\fifo[12] [7]), .A1(n_293), .B0(wr_data_i[7]), .B1(n_292)
  );
  AOI22XL g7640__7765(
      .Y(n_291), .A0(\fifo[14] [6]), .A1(n_277), .B0(\fifo[13] [6]), .B1(n_319)
  );
  AO22XL g7529__9867(
      .Y(n_290), .A0(\fifo[4] [4]), .A1(n_289), .B0(wr_data_i[4]), .B1(n_288)
  );
  AO22XL g7621__3377(
      .Y(n_287), .A0(\fifo[8] [6]), .A1(n_301), .B0(wr_data_i[6]), .B1(n_300)
  );
  AO22XL g7622__9719(
      .Y(n_286), .A0(\fifo[8] [7]), .A1(n_301), .B0(wr_data_i[7]), .B1(n_300)
  );
  AO22XL g7523__1591(
      .Y(n_285), .A0(\fifo[4] [2]), .A1(n_289), .B0(wr_data_i[2]), .B1(n_288)
  );
  AO22XL g7631__6789(
      .Y(n_284), .A0(\fifo[4] [0]), .A1(n_289), .B0(wr_data_i[0]), .B1(n_288)
  );
  AO22XL g7526__5927(
      .Y(n_283), .A0(\fifo[4] [3]), .A1(n_289), .B0(wr_data_i[3]), .B1(n_288)
  );
  SDFFHQX1 \rd_ptr_reg[3] (
      .Q(rd_ptr[3]), .D(n_106), .SE(scan_en), .SI(\fifo[7] [7]), .CK(clk_i)
  );
  SDFFHQX1 \rd_ptr_reg[2] (
      .Q(rd_ptr[2]), .D(n_105), .SE(scan_en), .SI(rd_ptr[3]), .CK(clk_i)
  );
  AO22XL g7532__2001(
      .Y(n_282), .A0(\fifo[4] [5]), .A1(n_289), .B0(wr_data_i[5]), .B1(n_288)
  );
  AOI22XL g7655__1122(
      .Y(n_281), .A0(\fifo[12] [6]), .A1(n_275), .B0(\fifo[11] [6]), .B1(n_320)
  );
  AO22XL g7537__2005(
      .Y(n_280), .A0(\fifo[4] [6]), .A1(n_289), .B0(wr_data_i[6]), .B1(n_288)
  );
  AO22XL g7541__9771(
      .Y(n_279), .A0(\fifo[4] [7]), .A1(n_289), .B0(wr_data_i[7]), .B1(n_288)
  );
  AOI22XL g7667__3457(
      .Y(n_278), .A0(\fifo[14] [0]), .A1(n_277), .B0(\fifo[13] [0]), .B1(n_319)
  );
  AOI22XL g7669__1279(
      .Y(n_276), .A0(\fifo[12] [0]), .A1(n_275), .B0(\fifo[11] [0]), .B1(n_320)
  );
  AOI22XL g7671__6179(
      .Y(n_274), .A0(\fifo[14] [1]), .A1(n_277), .B0(\fifo[11] [1]), .B1(n_320)
  );
  AOI22XL g7672__7837(
      .Y(n_273), .A0(\fifo[12] [1]), .A1(n_275), .B0(\fifo[13] [1]), .B1(n_319)
  );
  AOI22XL g7677__7557(
      .Y(n_272), .A0(\fifo[12] [4]), .A1(n_275), .B0(\fifo[11] [4]), .B1(n_320)
  );
  AO22XL g7546__7654(
      .Y(n_271), .A0(\fifo[12] [0]), .A1(n_293), .B0(wr_data_i[0]), .B1(n_292)
  );
  AOI22XL g7678__8867(
      .Y(n_270), .A0(\fifo[14] [3]), .A1(n_277), .B0(\fifo[13] [3]), .B1(n_319)
  );
  AOI22XL g7680__1377(
      .Y(n_269), .A0(\fifo[12] [3]), .A1(n_275), .B0(\fifo[11] [3]), .B1(n_320)
  );
  AOI22XL g7682__3717(
      .Y(n_268), .A0(\fifo[14] [4]), .A1(n_277), .B0(\fifo[13] [4]), .B1(n_319)
  );
  AOI22XL g7685__4599(
      .Y(n_267), .A0(\fifo[14] [5]), .A1(n_277), .B0(\fifo[13] [5]), .B1(n_319)
  );
  AOI22XL g7687__3779(
      .Y(n_266), .A0(\fifo[12] [5]), .A1(n_275), .B0(\fifo[11] [5]), .B1(n_320)
  );
  AO22XL g7550__2007(
      .Y(n_265), .A0(\fifo[12] [1]), .A1(n_293), .B0(wr_data_i[1]), .B1(n_292)
  );
  AO22XL g7551__1237(
      .Y(n_264), .A0(\fifo[12] [2]), .A1(n_293), .B0(wr_data_i[2]), .B1(n_292)
  );
  AO22XL g7553__1297(
      .Y(n_263), .A0(\fifo[12] [3]), .A1(n_293), .B0(wr_data_i[3]), .B1(n_292)
  );
  AO22XL g7554__2006(
      .Y(n_262), .A0(\fifo[12] [4]), .A1(n_293), .B0(wr_data_i[4]), .B1(n_292)
  );
  AO22XL g7556__2833(
      .Y(n_261), .A0(\fifo[12] [5]), .A1(n_293), .B0(wr_data_i[5]), .B1(n_292)
  );
  AO22XL g7600__7547(
      .Y(n_260), .A0(\fifo[2] [7]), .A1(n_258), .B0(wr_data_i[7]), .B1(n_257)
  );
  AO22XL g7578__7765(
      .Y(n_259), .A0(\fifo[2] [2]), .A1(n_258), .B0(wr_data_i[2]), .B1(n_257)
  );
  AO22XL g7579__9867(
      .Y(n_256), .A0(\fifo[6] [1]), .A1(n_249), .B0(wr_data_i[1]), .B1(n_248)
  );
  AO22XL g7501__3377(
      .Y(n_255), .A0(\fifo[5] [5]), .A1(n_241), .B0(wr_data_i[5]), .B1(n_364)
  );
  AO22XL g7580__9719(
      .Y(n_254), .A0(\fifo[14] [2]), .A1(n_252), .B0(wr_data_i[2]), .B1(n_251)
  );
  AO22XL g7581__1591(
      .Y(n_253), .A0(\fifo[14] [3]), .A1(n_252), .B0(wr_data_i[3]), .B1(n_251)
  );
  AO22XL g7582__6789(
      .Y(n_250), .A0(\fifo[6] [2]), .A1(n_249), .B0(wr_data_i[2]), .B1(n_248)
  );
  AO22XL g7583__5927(
      .Y(n_247), .A0(\fifo[14] [4]), .A1(n_252), .B0(wr_data_i[4]), .B1(n_251)
  );
  AO22XL g7502__2001(
      .Y(n_246), .A0(\fifo[13] [0]), .A1(n_217), .B0(wr_data_i[0]), .B1(n_216)
  );
  AO22XL g7584__1122(
      .Y(n_245), .A0(\fifo[0] [4]), .A1(n_227), .B0(wr_data_i[4]), .B1(n_226)
  );
  AO22XL g7585__2005(
      .Y(n_244), .A0(\fifo[14] [5]), .A1(n_252), .B0(wr_data_i[5]), .B1(n_251)
  );
  AO22XL g7586__9771(
      .Y(n_243), .A0(\fifo[6] [3]), .A1(n_249), .B0(wr_data_i[3]), .B1(n_248)
  );
  AO22XL g7504__3457(
      .Y(n_242), .A0(\fifo[5] [4]), .A1(n_241), .B0(wr_data_i[4]), .B1(n_364)
  );
  AO22XL g7587__1279(
      .Y(n_239), .A0(\fifo[14] [6]), .A1(n_252), .B0(wr_data_i[6]), .B1(n_251)
  );
  AO22XL g7616__6179(
      .Y(n_238), .A0(\fifo[1] [0]), .A1(n_203), .B0(wr_data_i[0]), .B1(n_202)
  );
  AO22XL g7588__7837(
      .Y(n_237), .A0(\fifo[2] [3]), .A1(n_258), .B0(wr_data_i[3]), .B1(n_257)
  );
  AO22XL g7610__7557(
      .Y(n_236), .A0(\fifo[3] [1]), .A1(n_212), .B0(wr_data_i[1]), .B1(n_362)
  );
  AO22XL g7589__7654(
      .Y(n_235), .A0(\fifo[14] [7]), .A1(n_252), .B0(wr_data_i[7]), .B1(n_251)
  );
  AO22XL g7590__8867(
      .Y(n_234), .A0(\fifo[6] [4]), .A1(n_249), .B0(wr_data_i[4]), .B1(n_248)
  );
  AO22XL g7506__1377(
      .Y(n_233), .A0(\fifo[2] [0]), .A1(n_258), .B0(wr_data_i[0]), .B1(n_257)
  );
  AO22XL g7591__3717(
      .Y(n_232), .A0(\fifo[2] [4]), .A1(n_258), .B0(wr_data_i[4]), .B1(n_257)
  );
  AO22XL g7592__4599(
      .Y(n_231), .A0(\fifo[6] [5]), .A1(n_249), .B0(wr_data_i[5]), .B1(n_248)
  );
  AO22XL g7593__3779(
      .Y(n_230), .A0(\fifo[6] [6]), .A1(n_249), .B0(wr_data_i[6]), .B1(n_248)
  );
  AO22XL g7594__2007(
      .Y(n_229), .A0(\fifo[6] [7]), .A1(n_249), .B0(wr_data_i[7]), .B1(n_248)
  );
  AO22XL g7595__1237(
      .Y(n_228), .A0(\fifo[0] [5]), .A1(n_227), .B0(wr_data_i[5]), .B1(n_226)
  );
  AO22XL g7596__1297(
      .Y(n_225), .A0(\fifo[2] [5]), .A1(n_258), .B0(wr_data_i[5]), .B1(n_257)
  );
  AO22XL g7609__2006(
      .Y(n_224), .A0(\fifo[0] [7]), .A1(n_227), .B0(wr_data_i[7]), .B1(n_226)
  );
  AO22XL g7597__2833(
      .Y(n_223), .A0(\fifo[7] [0]), .A1(n_221), .B0(wr_data_i[0]), .B1(n_220)
  );
  AO22XL g7598__7547(
      .Y(n_222), .A0(\fifo[7] [1]), .A1(n_221), .B0(wr_data_i[1]), .B1(n_220)
  );
  AO22XL g7599__7765(
      .Y(n_219), .A0(\fifo[7] [2]), .A1(n_221), .B0(wr_data_i[2]), .B1(n_220)
  );
  AO22XL g7500__9867(
      .Y(n_218), .A0(\fifo[13] [1]), .A1(n_217), .B0(wr_data_i[1]), .B1(n_216)
  );
  AO22XL g7601__3377(
      .Y(n_215), .A0(\fifo[7] [3]), .A1(n_221), .B0(wr_data_i[3]), .B1(n_220)
  );
  AO22XL g7602__9719(
      .Y(n_214), .A0(\fifo[2] [6]), .A1(n_258), .B0(wr_data_i[6]), .B1(n_257)
  );
  AO22XL g7603__1591(
      .Y(n_213), .A0(\fifo[3] [0]), .A1(n_212), .B0(wr_data_i[0]), .B1(n_362)
  );
  AO22XL g7604__6789(
      .Y(n_210), .A0(\fifo[7] [4]), .A1(n_221), .B0(wr_data_i[4]), .B1(n_220)
  );
  AO22XL g7605__5927(
      .Y(n_209), .A0(\fifo[7] [5]), .A1(n_221), .B0(wr_data_i[5]), .B1(n_220)
  );
  AO22XL g7606__2001(
      .Y(n_208), .A0(\fifo[7] [6]), .A1(n_221), .B0(wr_data_i[6]), .B1(n_220)
  );
  AO22XL g7607__1122(
      .Y(n_207), .A0(\fifo[7] [7]), .A1(n_221), .B0(wr_data_i[7]), .B1(n_220)
  );
  AO22XL g7612__2005(
      .Y(n_206), .A0(\fifo[0] [6]), .A1(n_227), .B0(wr_data_i[6]), .B1(n_226)
  );
  AO22XL g7613__9771(
      .Y(n_205), .A0(\fifo[3] [2]), .A1(n_212), .B0(wr_data_i[2]), .B1(n_362)
  );
  AO22XL g7634__3457(
      .Y(n_204), .A0(\fifo[1] [1]), .A1(n_203), .B0(wr_data_i[1]), .B1(n_202)
  );
  AO22XL g7633__1279(
      .Y(n_201), .A0(\fifo[9] [6]), .A1(n_191), .B0(wr_data_i[6]), .B1(n_190)
  );
  AO22XL g7619__6179(
      .Y(n_200), .A0(\fifo[3] [3]), .A1(n_212), .B0(wr_data_i[3]), .B1(n_362)
  );
  AO22XL g7519__7837(
      .Y(n_199), .A0(\fifo[10] [1]), .A1(n_194), .B0(wr_data_i[1]), .B1(n_193)
  );
  AO22XL g7620__7557(
      .Y(n_198), .A0(\fifo[3] [4]), .A1(n_212), .B0(wr_data_i[4]), .B1(n_362)
  );
  AO22XL g7520__7654(
      .Y(n_197), .A0(\fifo[0] [0]), .A1(n_227), .B0(wr_data_i[0]), .B1(n_226)
  );
  AO22XL g7623__8867(
      .Y(n_196), .A0(\fifo[3] [5]), .A1(n_212), .B0(wr_data_i[5]), .B1(n_362)
  );
  AO22XL g7521__1377(
      .Y(n_195), .A0(\fifo[10] [2]), .A1(n_194), .B0(wr_data_i[2]), .B1(n_193)
  );
  AO22XL g7624__3717(
      .Y(n_192), .A0(\fifo[9] [0]), .A1(n_191), .B0(wr_data_i[0]), .B1(n_190)
  );
  AO22XL g7625__4599(
      .Y(n_189), .A0(\fifo[9] [1]), .A1(n_191), .B0(wr_data_i[1]), .B1(n_190)
  );
  AO22XL g7522__3779(
      .Y(n_188), .A0(\fifo[10] [3]), .A1(n_194), .B0(wr_data_i[3]), .B1(n_193)
  );
  AO22XL g7626__2007(
      .Y(n_187), .A0(\fifo[3] [6]), .A1(n_212), .B0(wr_data_i[6]), .B1(n_362)
  );
  AO22XL g7627__1237(
      .Y(n_186), .A0(\fifo[9] [2]), .A1(n_191), .B0(wr_data_i[2]), .B1(n_190)
  );
  AO22XL g7628__1297(
      .Y(n_185), .A0(\fifo[9] [3]), .A1(n_191), .B0(wr_data_i[3]), .B1(n_190)
  );
  AO22XL g7629__2006(
      .Y(n_184), .A0(\fifo[3] [7]), .A1(n_212), .B0(wr_data_i[7]), .B1(n_362)
  );
  AO22XL g7524__2833(
      .Y(n_183), .A0(\fifo[10] [4]), .A1(n_194), .B0(wr_data_i[4]), .B1(n_193)
  );
  AO22XL g7630__7547(
      .Y(n_182), .A0(\fifo[9] [4]), .A1(n_191), .B0(wr_data_i[4]), .B1(n_190)
  );
  AO22XL g7525__7765(
      .Y(n_181), .A0(\fifo[1] [3]), .A1(n_203), .B0(wr_data_i[3]), .B1(n_202)
  );
  AO22XL g7632__9867(
      .Y(n_180), .A0(\fifo[9] [5]), .A1(n_191), .B0(wr_data_i[5]), .B1(n_190)
  );
  SDFFHQX1 \rd_ptr_reg[1] (
      .Q(rd_ptr[1]), .D(n_82), .SE(scan_en), .SI(rd_ptr[2]), .CK(clk_i)
  );
  SDFFHQX1 \rd_ptr_reg[0] (
      .Q(rd_ptr[0]), .D(n_81), .SE(scan_en), .SI(rd_ptr[1]), .CK(clk_i)
  );
  AO22XL g7635__3377(
      .Y(n_179), .A0(\fifo[1] [2]), .A1(n_203), .B0(wr_data_i[2]), .B1(n_202)
  );
  AO22XL g7527__9719(
      .Y(n_178), .A0(\fifo[10] [5]), .A1(n_194), .B0(wr_data_i[5]), .B1(n_193)
  );
  AO22XL g7636__1591(
      .Y(n_177), .A0(\fifo[9] [7]), .A1(n_191), .B0(wr_data_i[7]), .B1(n_190)
  );
  AO22XL g7637__6789(
      .Y(n_176), .A0(\fifo[10] [0]), .A1(n_194), .B0(wr_data_i[0]), .B1(n_193)
  );
  AO22XL g7528__5927(
      .Y(n_175), .A0(\fifo[10] [6]), .A1(n_194), .B0(wr_data_i[6]), .B1(n_193)
  );
  AO22XL g7639__2001(
      .Y(n_174), .A0(\fifo[5] [7]), .A1(n_241), .B0(wr_data_i[7]), .B1(n_364)
  );
  AO22XL g7641__1122(
      .Y(n_173), .A0(wr_data_i[5]), .A1(n_170), .B0(\fifo[15] [5]), .B1(n_169)
  );
  AO22XL g7530__2005(
      .Y(n_172), .A0(\fifo[10] [7]), .A1(n_194), .B0(wr_data_i[7]), .B1(n_193)
  );
  AO22XL g7642__9771(
      .Y(n_171), .A0(wr_data_i[4]), .A1(n_170), .B0(\fifo[15] [4]), .B1(n_169)
  );
  AO22XL g7643__3457(
      .Y(n_168), .A0(wr_data_i[3]), .A1(n_170), .B0(\fifo[15] [3]), .B1(n_169)
  );
  AO22XL g7644__1279(
      .Y(n_167), .A0(wr_data_i[2]), .A1(n_170), .B0(\fifo[15] [2]), .B1(n_169)
  );
  AO22XL g7645__6179(
      .Y(n_166), .A0(wr_data_i[1]), .A1(n_170), .B0(\fifo[15] [1]), .B1(n_169)
  );
  AO22XL g7531__7837(
      .Y(n_165), .A0(\fifo[11] [0]), .A1(n_162), .B0(wr_data_i[0]), .B1(n_161)
  );
  NOR2X1 g7646__7557(
      .Y(n_164), .A(rst_i), .B(n_84)
  );
  AO22XL g7533__7654(
      .Y(n_163), .A0(\fifo[11] [1]), .A1(n_162), .B0(wr_data_i[1]), .B1(n_161)
  );
  AO22XL g7534__8867(
      .Y(n_160), .A0(\fifo[1] [4]), .A1(n_203), .B0(wr_data_i[4]), .B1(n_202)
  );
  AO22XL g7535__1377(
      .Y(n_159), .A0(\fifo[1] [5]), .A1(n_203), .B0(wr_data_i[5]), .B1(n_202)
  );
  AO22XL g7653__3717(
      .Y(n_158), .A0(wr_data_i[0]), .A1(n_170), .B0(\fifo[15] [0]), .B1(n_169)
  );
  AO22XL g7536__4599(
      .Y(n_157), .A0(\fifo[11] [2]), .A1(n_162), .B0(wr_data_i[2]), .B1(n_161)
  );
  AOI22XL g7654__3779(
      .Y(n_156), .A0(\fifo[8] [6]), .A1(n_332), .B0(\fifo[7] [6]), .B1(n_153)
  );
  AOI22XL g7656__2007(
      .Y(n_155), .A0(\fifo[10] [6]), .A1(n_151), .B0(\fifo[9] [6]), .B1(n_331)
  );
  AOI22X1 g7657__1237(
      .Y(n_154), .A0(\fifo[12] [7]), .A1(n_275), .B0(\fifo[7] [7]), .B1(n_153)
  );
  AO22XL g7658__1297(
      .Y(n_152), .A0(\fifo[10] [7]), .A1(n_151), .B0(\fifo[14] [7]), .B1(n_277)
  );
  AO22XL g7659__2006(
      .Y(n_150), .A0(wr_data_i[7]), .A1(n_170), .B0(\fifo[15] [7]), .B1(n_169)
  );
  AO22XL g7538__2833(
      .Y(n_149), .A0(\fifo[11] [3]), .A1(n_162), .B0(wr_data_i[3]), .B1(n_161)
  );
  AO22XL g7539__7547(
      .Y(n_148), .A0(\fifo[11] [4]), .A1(n_162), .B0(wr_data_i[4]), .B1(n_161)
  );
  AO22XL g7540__7765(
      .Y(n_147), .A0(\fifo[1] [6]), .A1(n_203), .B0(wr_data_i[6]), .B1(n_202)
  );
  AOI22XL g7666__9867(
      .Y(n_146), .A0(\fifo[10] [3]), .A1(n_151), .B0(\fifo[9] [3]), .B1(n_331)
  );
  AO22XL g7542__3377(
      .Y(n_145), .A0(\fifo[11] [5]), .A1(n_162), .B0(wr_data_i[5]), .B1(n_161)
  );
  AOI22XL g7668__9719(
      .Y(n_144), .A0(\fifo[8] [0]), .A1(n_332), .B0(\fifo[7] [0]), .B1(n_153)
  );
  AOI22XL g7670__1591(
      .Y(n_143), .A0(\fifo[10] [0]), .A1(n_151), .B0(\fifo[9] [0]), .B1(n_331)
  );
  AO22XL g7543__6789(
      .Y(n_142), .A0(\fifo[11] [6]), .A1(n_162), .B0(wr_data_i[6]), .B1(n_161)
  );
  AO22XL g7544__5927(
      .Y(n_141), .A0(\fifo[5] [0]), .A1(n_241), .B0(wr_data_i[0]), .B1(n_364)
  );
  AOI22XL g7673__2001(
      .Y(n_140), .A0(\fifo[10] [1]), .A1(n_151), .B0(\fifo[9] [1]), .B1(n_331)
  );
  AOI22XL g7674__1122(
      .Y(n_139), .A0(\fifo[8] [1]), .A1(n_332), .B0(\fifo[7] [1]), .B1(n_153)
  );
  AO22XL g7545__2005(
      .Y(n_138), .A0(\fifo[11] [7]), .A1(n_162), .B0(wr_data_i[7]), .B1(n_161)
  );
  AOI22X1 g7675__9771(
      .Y(n_137), .A0(\fifo[12] [2]), .A1(n_275), .B0(\fifo[7] [2]), .B1(n_153)
  );
  AO22XL g7676__3457(
      .Y(n_136), .A0(\fifo[10] [2]), .A1(n_151), .B0(\fifo[14] [2]), .B1(n_277)
  );
  AO22XL g7679__1279(
      .Y(n_135), .A0(wr_data_i[6]), .A1(n_170), .B0(\fifo[15] [6]), .B1(n_169)
  );
  AOI22XL g7681__6179(
      .Y(n_134), .A0(\fifo[8] [3]), .A1(n_332), .B0(\fifo[7] [3]), .B1(n_153)
  );
  AO22XL g7547__7837(
      .Y(n_133), .A0(\fifo[0] [1]), .A1(n_227), .B0(wr_data_i[1]), .B1(n_226)
  );
  AOI22XL g7683__7557(
      .Y(n_132), .A0(\fifo[8] [4]), .A1(n_332), .B0(\fifo[7] [4]), .B1(n_153)
  );
  AO22XL g7548__7654(
      .Y(n_131), .A0(\fifo[1] [7]), .A1(n_203), .B0(wr_data_i[7]), .B1(n_202)
  );
  AOI22XL g7684__8867(
      .Y(n_130), .A0(\fifo[10] [4]), .A1(n_151), .B0(\fifo[9] [4]), .B1(n_331)
  );
  AOI22XL g7686__1377(
      .Y(n_129), .A0(\fifo[8] [5]), .A1(n_332), .B0(\fifo[7] [5]), .B1(n_153)
  );
  AO22XL g7549__3717(
      .Y(n_128), .A0(\fifo[5] [1]), .A1(n_241), .B0(wr_data_i[1]), .B1(n_364)
  );
  AOI22XL g7688__4599(
      .Y(n_127), .A0(\fifo[10] [5]), .A1(n_151), .B0(\fifo[9] [5]), .B1(n_331)
  );
  AO22XL g7552__3779(
      .Y(n_126), .A0(\fifo[5] [2]), .A1(n_241), .B0(wr_data_i[2]), .B1(n_364)
  );
  AO22XL g7555__2007(
      .Y(n_125), .A0(\fifo[5] [3]), .A1(n_241), .B0(wr_data_i[3]), .B1(n_364)
  );
  AO22XL g7496__1237(
      .Y(n_124), .A0(\fifo[13] [3]), .A1(n_217), .B0(wr_data_i[3]), .B1(n_216)
  );
  AO22XL g7569__1297(
      .Y(n_123), .A0(\fifo[13] [4]), .A1(n_217), .B0(wr_data_i[4]), .B1(n_216)
  );
  AO22XL g7570__2006(
      .Y(n_122), .A0(\fifo[13] [5]), .A1(n_217), .B0(wr_data_i[5]), .B1(n_216)
  );
  AO22XL g7571__2833(
      .Y(n_121), .A0(\fifo[13] [6]), .A1(n_217), .B0(wr_data_i[6]), .B1(n_216)
  );
  AO22XL g7497__7547(
      .Y(n_120), .A0(\fifo[5] [6]), .A1(n_241), .B0(wr_data_i[6]), .B1(n_364)
  );
  AO22XL g7572__7765(
      .Y(n_119), .A0(\fifo[6] [0]), .A1(n_249), .B0(wr_data_i[0]), .B1(n_248)
  );
  AO22XL g7573__9867(
      .Y(n_118), .A0(\fifo[13] [7]), .A1(n_217), .B0(wr_data_i[7]), .B1(n_216)
  );
  AO22XL g7574__3377(
      .Y(n_117), .A0(\fifo[2] [1]), .A1(n_258), .B0(wr_data_i[1]), .B1(n_257)
  );
  AO22XL g7498__9719(
      .Y(n_116), .A0(\fifo[13] [2]), .A1(n_217), .B0(wr_data_i[2]), .B1(n_216)
  );
  AO22XL g7575__1591(
      .Y(n_115), .A0(\fifo[14] [0]), .A1(n_252), .B0(wr_data_i[0]), .B1(n_251)
  );
  AO22XL g7499__6789(
      .Y(n_114), .A0(\fifo[0] [2]), .A1(n_227), .B0(wr_data_i[2]), .B1(n_226)
  );
  AO22XL g7576__5927(
      .Y(n_113), .A0(\fifo[14] [1]), .A1(n_252), .B0(wr_data_i[1]), .B1(n_251)
  );
  AO22XL g7577__2001(
      .Y(n_112), .A0(\fifo[0] [3]), .A1(n_227), .B0(wr_data_i[3]), .B1(n_226)
  );
  AOI22XL g7725__1122(
      .Y(n_111), .A0(\fifo[1] [7]), .A1(n_110), .B0(\fifo[5] [7]), .B1(n_306)
  );
  AOI22X1 g7727__2005(
      .Y(n_109), .A0(\fifo[0] [4]), .A1(n_315), .B0(\fifo[1] [4]), .B1(n_110)
  );
  AOI22XL g7726__9771(
      .Y(n_108), .A0(\fifo[2] [7]), .A1(n_325), .B0(\fifo[4] [7]), .B1(n_311)
  );
  XNOR2X1 g7689__3457(
      .Y(n_107), .A(rd_toggle_flag), .B(n_55)
  );
  OAI22X1 g7690__1279(
      .Y(n_106), .A0(n_33), .A1(n_103), .B0(n_17), .B1(n_104)
  );
  OAI32X1 g7691__6179(
      .Y(n_105), .A0(rd_ptr[2]), .A1(n_54), .A2(n_104), .B0(n_5), .B1(n_103)
  );
  AOI22X1 g7723__7837(
      .Y(n_102), .A0(\fifo[2] [6]), .A1(n_325), .B0(\fifo[6] [6]), .B1(n_101)
  );
  AOI22X1 g7724__7557(
      .Y(n_100), .A0(\fifo[2] [5]), .A1(n_325), .B0(\fifo[1] [5]), .B1(n_110)
  );
  AO22XL g7728__7654(
      .Y(n_99), .A0(\fifo[6] [3]), .A1(n_101), .B0(\fifo[5] [3]), .B1(n_306)
  );
  SDFFHQX1 \wr_ptr_reg[0] (
      .Q(wr_ptr[0]), .D(n_67), .SE(scan_en), .SI(rd_ptr[0]), .CK(clk_i)
  );
  SDFFHQX1 \wr_ptr_reg[1] (
      .Q(wr_ptr[1]), .D(n_77), .SE(scan_en), .SI(wr_ptr[0]), .CK(clk_i)
  );
  SDFFHQX1 \wr_ptr_reg[3] (
      .Q(wr_ptr[3]), .D(n_78), .SE(scan_en), .SI(wr_ptr[1]), .CK(clk_i)
  );
  SDFFHQX1 \wr_ptr_reg[2] (
      .Q(wr_ptr[2]), .D(n_76), .SE(scan_en), .SI(wr_ptr[3]), .CK(clk_i)
  );
  AOI22X1 g7742__8867(
      .Y(n_98), .A0(\fifo[1] [1]), .A1(n_110), .B0(\fifo[3] [1]), .B1(n_310)
  );
  AOI22XL g7730__1377(
      .Y(n_97), .A0(\fifo[6] [2]), .A1(n_101), .B0(\fifo[5] [2]), .B1(n_306)
  );
  AOI22XL g7731__3717(
      .Y(n_96), .A0(\fifo[0] [7]), .A1(n_315), .B0(\fifo[3] [7]), .B1(n_310)
  );
  AOI22XL g7732__4599(
      .Y(n_95), .A0(\fifo[0] [2]), .A1(n_315), .B0(rd_data_o[2]), .B1(n_328)
  );
  AO22XL g7733__3779(
      .Y(n_94), .A0(\fifo[6] [5]), .A1(n_101), .B0(\fifo[5] [5]), .B1(n_306)
  );
  AOI22X1 g7734__2007(
      .Y(n_93), .A0(\fifo[6] [0]), .A1(n_101), .B0(\fifo[3] [0]), .B1(n_310)
  );
  AO22XL g7735__1237(
      .Y(n_92), .A0(\fifo[2] [0]), .A1(n_325), .B0(\fifo[4] [0]), .B1(n_311)
  );
  AOI22XL g7736__1297(
      .Y(n_91), .A0(\fifo[2] [2]), .A1(n_325), .B0(\fifo[1] [2]), .B1(n_110)
  );
  AOI22XL g7737__2006(
      .Y(n_90), .A0(\fifo[4] [2]), .A1(n_311), .B0(\fifo[3] [2]), .B1(n_310)
  );
  AO22XL g7738__2833(
      .Y(n_89), .A0(\fifo[1] [6]), .A1(n_110), .B0(\fifo[3] [6]), .B1(n_310)
  );
  AO22XL g7739__7547(
      .Y(n_88), .A0(\fifo[6] [4]), .A1(n_101), .B0(\fifo[5] [4]), .B1(n_306)
  );
  AO22XL g7740__7765(
      .Y(n_87), .A0(\fifo[4] [1]), .A1(n_311), .B0(\fifo[5] [1]), .B1(n_306)
  );
  AOI22XL g7741__9867(
      .Y(n_86), .A0(\fifo[6] [7]), .A1(n_101), .B0(rd_data_o[7]), .B1(n_328)
  );
  AOI22X1 g7729__3377(
      .Y(n_85), .A0(\fifo[0] [3]), .A1(n_315), .B0(\fifo[1] [3]), .B1(n_110)
  );
  XNOR2X1 g7719__9719(
      .Y(n_84), .A(wr_toggle_flag), .B(n_56)
  );
  NOR2X1 g7716__1591(
      .Y(n_288), .A(n_69), .B(n_83)
  );
  NOR2X1 g7743__6789(
      .Y(n_300), .A(n_73), .B(n_83)
  );
  NOR2X1 g7717__5927(
      .Y(n_292), .A(n_65), .B(n_83)
  );
  OAI22X1 g7722__2001(
      .Y(n_82), .A0(n_0), .A1(n_104), .B0(n_6), .B1(n_80)
  );
  OAI22X1 g7721__1122(
      .Y(n_81), .A0(rd_ptr[0]), .A1(n_104), .B0(n_37), .B1(n_80)
  );
  NOR2X1 g7751__2005(
      .Y(n_327), .A(n_79), .B(n_62)
  );
  NOR2X1 g7756__9771(
      .Y(n_319), .A(n_79), .B(n_57)
  );
  NOR2X1 g7757__3457(
      .Y(n_320), .A(n_79), .B(n_59)
  );
  NOR2X1 g7693__1279(
      .Y(n_78), .A(rst_i), .B(n_47)
  );
  NOR2X1 g7694__6179(
      .Y(n_77), .A(rst_i), .B(n_38)
  );
  NOR2X1 g7695__7837(
      .Y(n_76), .A(rst_i), .B(n_39)
  );
  AND2X1 g7698__7557(
      .Y(n_226), .A(n_50), .B(n_74)
  );
  NAND2X1 g7703__7654(
      .Y(n_203), .A(n_64), .B(n_72)
  );
  AND2X1 g7697__1377(
      .Y(n_202), .A(n_75), .B(n_74)
  );
  AND2X1 g7754__3717(
      .Y(n_331), .A(n_58), .B(n_53)
  );
  NOR2BX1 g7699__4599(
      .Y(n_190), .AN(n_75), .B(n_73)
  );
  NAND2X1 g7700__3779(
      .Y(n_221), .A(n_71), .B(n_72)
  );
  NAND2X1 g7701__2007(
      .Y(n_162), .A(n_70), .B(n_61)
  );
  NAND2X1 g7702__1237(
      .Y(n_249), .A(n_71), .B(n_66)
  );
  NAND2X1 g7705__1297(
      .Y(n_194), .A(n_70), .B(n_63)
  );
  NOR2X1 g7706__2006(
      .Y(n_248), .A(n_69), .B(n_68)
  );
  NOR2X1 g7707__2833(
      .Y(n_193), .A(n_73), .B(n_68)
  );
  NOR2X1 g7720__7547(
      .Y(n_67), .A(rst_i), .B(n_46)
  );
  NAND2X1 g7709__7765(
      .Y(n_258), .A(n_70), .B(n_66)
  );
  NOR2BX1 g7710__9867(
      .Y(n_216), .AN(n_75), .B(n_65)
  );
  NAND2X1 g7712__3377(
      .Y(n_227), .A(n_64), .B(n_66)
  );
  NAND2X1 g7715__9719(
      .Y(n_301), .A(n_64), .B(n_63)
  );
  NAND2X1 g7718__1591(
      .Y(n_212), .A(n_70), .B(n_72)
  );
  NOR2BX1 g7749__6789(
      .Y(n_277), .AN(n_60), .B(n_62)
  );
  NOR2X1 g7708__5927(
      .Y(n_251), .A(n_65), .B(n_68)
  );
  NAND2X1 g7744__2001(
      .Y(n_252), .A(n_71), .B(n_63)
  );
  NAND2X1 g7745__1122(
      .Y(n_191), .A(n_64), .B(n_61)
  );
  NOR2BX1 g7750__9771(
      .Y(n_151), .AN(n_60), .B(n_59)
  );
  AND2X1 g7752__3457(
      .Y(n_332), .A(n_58), .B(n_60)
  );
  NOR2BX1 g7753__1279(
      .Y(n_275), .AN(n_60), .B(n_57)
  );
  NOR2X1 g7755__6179(
      .Y(n_169), .A(rst_i), .B(n_56)
  );
  NOR3X1 g7768__7837(
      .Y(n_55), .A(n_16), .B(n_41), .C(n_4)
  );
  AOI21X1 g7767__7557(
      .Y(n_103), .A0(n_54), .A1(n_29), .B0(n_328)
  );
  INVX1 g7776(
      .Y(n_79), .A(n_53)
  );
  NOR2X1 g7780__7654(
      .Y(n_306), .A(n_52), .B(n_57)
  );
  NOR2X1 g7781__8867(
      .Y(n_101), .A(n_51), .B(n_62)
  );
  NOR2X1 g7782__1377(
      .Y(n_310), .A(n_52), .B(n_59)
  );
  NOR2X1 g7783__3717(
      .Y(n_153), .A(n_52), .B(n_62)
  );
  NOR2X1 g7789__4599(
      .Y(n_311), .A(n_51), .B(n_57)
  );
  NOR2X1 g7790__3779(
      .Y(n_325), .A(n_51), .B(n_59)
  );
  NOR2X1 g7775__2007(
      .Y(n_161), .A(n_73), .B(n_49)
  );
  SDFFHQX8 error_o_reg(
      .Q(error_o), .D(n_32), .SE(scan_en), .SI(wr_ptr[2]), .CK(clk_i)
  );
  INVX1 g7761(
      .Y(n_83), .A(n_50)
  );
  NOR2BX1 g7779__1237(
      .Y(n_110), .AN(n_58), .B(n_52)
  );
  NOR2X1 g7758__1297(
      .Y(n_220), .A(n_69), .B(n_49)
  );
  NAND2X1 g7704__2006(
      .Y(n_241), .A(n_48), .B(n_72)
  );
  NOR2BX1 g7791__2833(
      .Y(n_315), .AN(n_58), .B(n_51)
  );
  NAND2X1 g7713__7547(
      .Y(n_289), .A(n_48), .B(n_66)
  );
  NAND2X1 g7714__7765(
      .Y(n_293), .A(n_48), .B(n_63)
  );
  NAND2X1 g7746__9867(
      .Y(n_217), .A(n_48), .B(n_61)
  );
  NOR2X1 g7759__3377(
      .Y(n_170), .A(n_65), .B(n_49)
  );
  AND2X1 g7711__9719(
      .Y(n_257), .A(n_36), .B(n_74)
  );
  AOI22X1 g7765__1591(
      .Y(n_47), .A0(n_21), .A1(n_45), .B0(wr_ptr[3]), .B1(n_44)
  );
  AOI22X1 g7766__6789(
      .Y(n_46), .A0(n_9), .A1(n_45), .B0(wr_ptr[0]), .B1(n_44)
  );
  NOR2X1 g7772__5927(
      .Y(n_50), .A(n_34), .B(n_35)
  );
  OAI21X1 g7769__2001(
      .Y(n_71), .A0(n_14), .A1(n_363), .B0(n_42)
  );
  OAI21X1 g7773__1122(
      .Y(n_70), .A0(wr_ptr[2]), .A1(n_363), .B0(n_42)
  );
  OAI21X1 g7774__2005(
      .Y(n_64), .A0(wr_ptr[2]), .A1(n_28), .B0(n_42)
  );
  NOR2X1 g7777__9771(
      .Y(n_60), .A(rd_ptr[0]), .B(n_41)
  );
  AOI22X1 g7762__3457(
      .Y(n_39), .A0(n_15), .A1(n_45), .B0(wr_ptr[2]), .B1(n_44)
  );
  AOI22X1 g7764__1279(
      .Y(n_38), .A0(n_2), .A1(n_45), .B0(wr_ptr[1]), .B1(n_44)
  );
  INVX1 g7785(
      .Y(n_80), .A(n_328)
  );
  NOR2X1 g7778__6179(
      .Y(n_53), .A(n_37), .B(n_41)
  );
  NOR3X1 g7787__7837(
      .Y(n_56), .A(n_18), .B(n_65), .C(n_44)
  );
  INVX1 g7760(
      .Y(n_68), .A(n_36)
  );
  NOR2X1 g7747__7557(
      .Y(n_75), .A(n_8), .B(n_35)
  );
  NOR3X1 g7771__7654(
      .Y(n_36), .A(n_363), .B(rst_i), .C(n_34)
  );
  NAND3X1 g7804__8867(
      .Y(n_51), .A(n_33), .B(n_37), .C(n_31)
  );
  NAND3X1 g7788__1377(
      .Y(n_49), .A(n_19), .B(n_42), .C(n_45)
  );
  OAI22X1 g7763__3717(
      .Y(n_32), .A0(rst_i), .A1(n_25), .B0(n_31), .B1(n_26)
  );
  NAND3X1 g7803__4599(
      .Y(n_52), .A(rd_ptr[0]), .B(n_33), .C(n_31)
  );
  OAI2BB1X1 g7770__3779(
      .Y(n_48), .A0N(wr_ptr[2]), .A1N(n_30), .B0(n_42)
  );
  AOI21X1 g7792__2007(
      .Y(n_328), .A0(n_31), .A1(rd_en_i), .B0(rst_i)
  );
  NAND2X1 g7786__1237(
      .Y(n_35), .A(n_30), .B(n_42)
  );
  NAND2X1 g7798__1297(
      .Y(n_41), .A(rd_ptr[3]), .B(n_31)
  );
  INVX1 g7800(
      .Y(n_104), .A(n_29)
  );
  INVX1 g7793(
      .Y(n_28), .A(n_30)
  );
  INVX1 g7794(
      .Y(n_44), .A(n_45)
  );
  NOR2X1 g7805__2006(
      .Y(n_29), .A(empty_o), .B(n_26)
  );
  NAND2X1 g7795__7547(
      .Y(n_25), .A(full_o), .B(wr_en_i)
  );
  NOR2X1 g7796__7765(
      .Y(n_30), .A(wr_ptr[1]), .B(full_o)
  );
  INVX1 g7806(
      .Y(n_31), .A(empty_o)
  );
  NOR2BX1 g7799__9867(
      .Y(n_45), .AN(wr_en_i), .B(full_o)
  );
  AND3X6 g7807__3377(
      .Y(empty_o), .A(n_11), .B(n_12), .C(n_22)
  );
  AND2X6 g7810__9719(
      .Y(full_o), .A(n_13), .B(n_22)
  );
  AOI221X1 g7812__1591(
      .Y(n_22), .A0(rd_ptr[3]), .A1(n_20), .B0(wr_ptr[3]), .B1(n_33), .C0(n_10)
  );
  OAI221X1 g7801__6789(
      .Y(n_21), .A0(n_20), .A1(n_19), .B0(n_69), .B1(n_18), .C0(n_73)
  );
  MX2XL g7802__5927(
      .Y(n_17), .A(n_16), .B(rd_ptr[2]), .S0(rd_ptr[3])
  );
  OAI22X1 g7809__2001(
      .Y(n_15), .A0(wr_ptr[2]), .A1(n_18), .B0(n_14), .B1(n_19)
  );
  NOR2BX1 g7814__1122(
      .Y(n_13), .AN(n_12), .B(n_11)
  );
  OAI221X1 g7819__2005(
      .Y(n_10), .A0(wr_ptr[0]), .A1(n_37), .B0(rd_ptr[0]), .B1(n_9), .C0(n_7)
  );
  OAI21X1 g7816__9771(
      .Y(n_66), .A0(wr_ptr[3]), .A1(n_34), .B0(n_42)
  );
  OAI21X1 g7818__3457(
      .Y(n_63), .A0(n_20), .A1(n_34), .B0(n_42)
  );
  OAI21X1 g7815__1279(
      .Y(n_61), .A0(n_20), .A1(n_8), .B0(n_42)
  );
  OAI21X1 g7817__6179(
      .Y(n_72), .A0(wr_ptr[3]), .A1(n_8), .B0(n_42)
  );
  AOI22X1 g7826__7837(
      .Y(n_7), .A0(rd_ptr[1]), .A1(n_1), .B0(wr_ptr[1]), .B1(n_6)
  );
  OAI22X1 g7825__7557(
      .Y(n_12), .A0(rd_ptr[2]), .A1(wr_ptr[2]), .B0(n_14), .B1(n_5)
  );
  OR4X1 g7821__7654(
      .Y(n_62), .A(n_5), .B(n_6), .C(rst_i), .D(n_4)
  );
  NOR4X1 g7823__8867(
      .Y(n_58), .A(rd_ptr[1]), .B(rd_ptr[2]), .C(rst_i), .D(n_4)
  );
  OR4X1 g7822__1377(
      .Y(n_57), .A(rd_ptr[1]), .B(n_5), .C(rst_i), .D(n_4)
  );
  OAI22X1 g7828__3717(
      .Y(n_2), .A0(wr_ptr[1]), .A1(n_9), .B0(wr_ptr[0]), .B1(n_1)
  );
  AOI22X1 g7827__4599(
      .Y(n_0), .A0(rd_ptr[0]), .A1(n_6), .B0(rd_ptr[1]), .B1(n_37)
  );
  OR2XL g7811__3779(
      .Y(n_16), .A(n_5), .B(n_54)
  );
  OR4X1 g7820__2007(
      .Y(n_59), .A(rd_ptr[2]), .B(n_6), .C(rst_i), .D(n_4)
  );
  XNOR2X1 g7824__1237(
      .Y(n_11), .A(rd_toggle_flag), .B(wr_toggle_flag)
  );
  NAND2X1 g7831__1297(
      .Y(n_34), .A(n_9), .B(wr_en_i)
  );
  NAND2X1 g7836__2006(
      .Y(n_73), .A(wr_ptr[3]), .B(n_14)
  );
  NAND2X1 g7834__2833(
      .Y(n_26), .A(rd_en_i), .B(n_42)
  );
  INVX1 g7813(
      .Y(n_19), .A(n_18)
  );
  NAND2X1 g7837__7547(
      .Y(n_69), .A(n_20), .B(wr_ptr[2])
  );
  NAND2X1 g7835__7765(
      .Y(n_54), .A(rd_ptr[1]), .B(rd_ptr[0])
  );
  NAND2X1 g7832__9867(
      .Y(n_65), .A(wr_ptr[3]), .B(wr_ptr[2])
  );
  NAND2X1 g7829__3377(
      .Y(n_8), .A(wr_ptr[0]), .B(wr_en_i)
  );
  NOR2X1 g7830__9719(
      .Y(n_74), .A(wr_ptr[3]), .B(wr_ptr[2])
  );
  NAND2X1 g7838__1591(
      .Y(n_18), .A(wr_ptr[0]), .B(wr_ptr[1])
  );
  INVX1 g7841(
      .Y(n_1), .A(wr_ptr[1])
  );
  INVX1 g7848(
      .Y(n_14), .A(wr_ptr[2])
  );
  INVX1 g7847(
      .Y(n_5), .A(rd_ptr[2])
  );
  INVX1 g7844(
      .Y(n_20), .A(wr_ptr[3])
  );
  INVX1 g7845(
      .Y(n_42), .A(rst_i)
  );
  INVX1 g7840(
      .Y(n_33), .A(rd_ptr[3])
  );
  INVX1 g7846(
      .Y(n_9), .A(wr_ptr[0])
  );
  INVX1 g7843(
      .Y(n_37), .A(rd_ptr[0])
  );
  INVX1 g7839(
      .Y(n_4), .A(rd_en_i)
  );
  INVX1 g7842(
      .Y(n_6), .A(rd_ptr[1])
  );
  NOR2BX1 g2(
      .Y(n_362), .AN(n_74), .B(n_49)
  );
  NAND2BX1 g7996(
      .Y(n_363), .AN(full_o), .B(wr_ptr[1])
  );
  NOR2BX1 g7997(
      .Y(n_364), .AN(n_75), .B(n_69)
  );
  TLATNXL ts_lockup_latchn_clkc1_intno48_i(
      .Q(ts_lockup_latchn_clkc1_intno48_), .QN(), .D(\fifo[10] [6]), .GN(clk_i)
  );
  TLATNXL ts_lockup_latchn_clkc2_intno97_i(
      .Q(ts_lockup_latchn_clkc2_intno97_), .QN(), .D(\fifo[7] [6]), .GN(clk_i)
  );
  TLATNXL ts_lockup_latchn_clkc3_intno146_i(
      .Q(ts_lockup_latchn_clkc3_intno146_), .QN(), .D(error_o), .GN(clk_i)
  );
  DLY4X4 tessent_persistent_cell_buf_extsi147_i(
      .Y(ts_pbuf_extsi147_), .A(ts_si[0])
  );
  DLY4X4 tessent_persistent_cell_buf_extsi148_i(
      .Y(ts_pbuf_extsi148_), .A(ts_si[1])
  );
  DLY4X4 tessent_persistent_cell_buf_extsi149_i(
      .Y(ts_pbuf_extsi149_), .A(ts_si[2])
  );
endmodule

